import { PrismaClient, Difficulty, ProjectType } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const projects = [
  // Weather & Environment (10)
  {
    title: 'ESP32 Weather Station with OLED Display',
    description: 'Build a complete weather monitoring station using ESP32, DHT22 sensor, and SSD1306 OLED display. Measures temperature, humidity, and barometric pressure with real-time display.',
    type: ProjectType.IOT,
    category: 'Weather Station',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'DHT22', 'OLED', 'BME280', 'Weather'],
    components: ['ESP32 DevKit', 'DHT22 Temperature Sensor', 'BME280 Pressure Sensor', 'SSD1306 OLED 0.96"', 'Jumper Wires', 'Breadboard'],
    connections: ['Connect DHT22 VCC to 3.3V, GND to GND, DATA to GPIO4', 'Connect BME280 SDA to GPIO21, SCL to GPIO22', 'Connect OLED SDA to GPIO21, SCL to GPIO22, VCC to 3.3V'],
    steps: ['Wire the DHT22 sensor to ESP32', 'Connect BME280 via I2C', 'Wire the OLED display', 'Install required libraries (Adafruit_Sensor, DHT, Adafruit_SSD1306)', 'Upload the firmware code', 'Verify readings on OLED'],
    working: 'The ESP32 reads temperature and humidity from DHT22, pressure from BME280 via I2C, and displays all values on the OLED screen. Data is also sent to Pulse cloud via HTTP POST.',
    code: `#include <WiFi.h>\n#include <HTTPClient.h>\n#include "DHT.h"\n#include <Adafruit_BME280.h>\n\n#define DHTPIN 4\n#define DHTTYPE DHT22\n\nDHT dht(DHTPIN, DHTTYPE);\nAdafruit_BME280 bme;\n\nvoid setup() {\n  Serial.begin(115200);\n  dht.begin();\n  bme.begin(0x76);\n  WiFi.begin("SSID", "PASSWORD");\n}\n\nvoid loop() {\n  float temp = dht.readTemperature();\n  float hum = dht.readHumidity();\n  float pres = bme.readPressure() / 100.0F;\n  \n  HTTPClient http;\n  http.begin("https://pulse.io/api/data/upload");\n  http.POST("{\"field1\":" + String(temp) + ",\"field2\":" + String(hum) + "}");\n  http.end();\n  delay(60000);\n}`,
    fieldLabels: ['Temperature (°C)', 'Humidity (%)', 'Pressure (hPa)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Arduino Indoor Air Quality Monitor',
    description: 'Monitor indoor air quality using MQ-135 gas sensor with Arduino. Detects CO2, ammonia, benzene, and other harmful gases with LED indicator alerts.',
    type: ProjectType.IOT,
    category: 'Environment',
    difficulty: Difficulty.BEGINNER,
    duration: '2 hours',
    tags: ['Arduino', 'MQ-135', 'Air Quality', 'LED'],
    components: ['Arduino Uno', 'MQ-135 Gas Sensor', 'LED (Red, Green, Yellow)', '220Ω Resistors', 'Breadboard', 'Jumper Wires'],
    connections: ['MQ-135 AOUT to A0, VCC to 5V, GND to GND', 'Green LED to pin 8, Yellow to pin 9, Red to pin 10'],
    steps: ['Connect MQ-135 sensor to Arduino', 'Wire the three LED indicators', 'Upload the code', 'Calibrate sensor in fresh air', 'Test with different air sources'],
    working: 'The MQ-135 sensor outputs analog voltage proportional to gas concentration. Arduino reads this value and triggers appropriate LED: green for good air, yellow for moderate, red for poor.',
    fieldLabels: ['Air Quality Index', 'CO2 Level (ppm)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Solar-Powered Weather Node',
    description: 'Create an autonomous weather monitoring node powered by solar panel with battery management. Perfect for remote outdoor deployment.',
    type: ProjectType.IOT,
    category: 'Weather Station',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['ESP32', 'Solar', 'Battery', 'Weather', 'Low Power'],
    components: ['ESP32', 'Solar Panel 5V 1W', 'TP4056 Charging Module', '18650 Battery', 'DHT22', 'BMP280', 'Enclosure'],
    connections: ['Solar panel to TP4056 input', 'TP4056 battery output to ESP32 VIN', 'DHT22 to GPIO4, BMP280 to I2C'],
    steps: ['Assemble solar charging circuit', 'Wire sensors to ESP32', 'Program deep sleep mode', 'Test power consumption', 'Deploy in weatherproof enclosure'],
    working: 'Solar panel charges the 18650 battery through TP4056. ESP32 wakes from deep sleep every 15 minutes, reads sensors, transmits data, then sleeps again to conserve power.',
    fieldLabels: ['Temperature (°C)', 'Humidity (%)', 'Pressure (hPa)', 'Battery Voltage (V)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Smart Garden Soil Moisture Monitor',
    description: 'Monitor soil moisture levels in your garden with capacitive soil moisture sensor and get alerts when plants need watering.',
    type: ProjectType.IOT,
    category: 'Smart Garden',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['ESP32', 'Soil Moisture', 'Garden', 'Alerts'],
    components: ['ESP32', 'Capacitive Soil Moisture Sensor v1.2', 'Jumper Wires', 'Breadboard'],
    connections: ['Sensor VCC to 3.3V, GND to GND, AOUT to GPIO34'],
    steps: ['Connect soil moisture sensor', 'Upload code with WiFi credentials', 'Insert sensor into soil', 'Monitor readings on Pulse dashboard', 'Set up moisture threshold alerts'],
    working: 'The capacitive soil moisture sensor measures volumetric water content. Corrosion-resistant design lasts longer than resistive sensors. ESP32 reads analog value and sends to Pulse.',
    fieldLabels: ['Soil Moisture (%)', 'Soil Temperature (°C)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'UV Index Monitor with ESP32',
    description: 'Build a UV index monitoring station using VEML6075 UV sensor. Track UV-A and UV-B radiation levels in real-time.',
    type: ProjectType.IOT,
    category: 'Environment',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2-3 hours',
    tags: ['ESP32', 'VEML6075', 'UV', 'Health'],
    components: ['ESP32', 'VEML6075 UV Sensor', 'OLED Display', 'Breadboard', 'Jumper Wires'],
    connections: ['VEML6075 SDA to GPIO21, SCL to GPIO22, VCC to 3.3V', 'OLED to same I2C bus'],
    steps: ['Wire VEML6075 sensor via I2C', 'Connect OLED display', 'Install VEML6075 library', 'Upload firmware', 'Calibrate with known UV source'],
    working: 'VEML6075 measures both UV-A and UV-B radiation. The ESP32 calculates the UV index using the sensor readings and displays it along with safety recommendations.',
    fieldLabels: ['UV Index', 'UV-A (mW/cm²)', 'UV-B (mW/cm²)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Rain Detection & Alert System',
    description: 'Detect rainfall using a rain sensor module and send real-time alerts. Perfect for automated greenhouse or laundry alert systems.',
    type: ProjectType.IOT,
    category: 'Weather Station',
    difficulty: Difficulty.BEGINNER,
    duration: '1 hour',
    tags: ['Arduino', 'Rain Sensor', 'Alerts', 'Automation'],
    components: ['Arduino Nano', 'Rain Sensor Module', 'Buzzer', 'LED', 'Jumper Wires'],
    connections: ['Rain sensor DO to D2, AO to A0', 'Buzzer to D8, LED to D9'],
    steps: ['Connect rain sensor module', 'Wire buzzer and LED', 'Upload code', 'Test with water drops', 'Adjust sensitivity potentiometer'],
    working: 'Rain drops on the sensor board change its resistance. The module outputs digital and analog signals. Arduino triggers buzzer and LED when rain is detected.',
    fieldLabels: ['Rain Detected', 'Rain Intensity (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Wind Speed Anemometer',
    description: 'Build a DIY anemometer using hall effect sensor and 3D-printed cups. Measure wind speed accurately for weather stations.',
    type: ProjectType.IOT,
    category: 'Weather Station',
    difficulty: Difficulty.ADVANCED,
    duration: '6-8 hours',
    tags: ['ESP32', 'Hall Effect', '3D Print', 'Wind'],
    components: ['ESP32', 'A3144 Hall Effect Sensor', 'Neodymium Magnet', 'PVC Pipes', '3D Printed Cups', 'Bearings'],
    connections: ['Hall sensor output to GPIO14 (interrupt pin), VCC to 3.3V, GND to GND'],
    steps: ['3D print or fabricate cups', 'Assemble anemometer on bearings', 'Mount magnet and hall sensor', 'Wire to ESP32', 'Calibrate with known wind speed', 'Deploy outdoors'],
    working: 'Each rotation of the anemometer triggers the hall effect sensor. ESP32 counts pulses per time interval and converts to wind speed using the calibrated formula.',
    fieldLabels: ['Wind Speed (km/h)', 'Wind Gust (km/h)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Water Level Monitoring System',
    description: 'Monitor water tank levels using ultrasonic sensor. Get real-time percentage readings and low-level alerts.',
    type: ProjectType.IOT,
    category: 'Smart Home',
    difficulty: Difficulty.BEGINNER,
    duration: '2 hours',
    tags: ['ESP32', 'HC-SR04', 'Water Tank', 'Monitoring'],
    components: ['ESP32', 'HC-SR04 Ultrasonic Sensor', 'Jumper Wires', 'Waterproof Enclosure'],
    connections: ['HC-SR04 Trig to GPIO5, Echo to GPIO18, VCC to 5V, GND to GND'],
    steps: ['Mount ultrasonic sensor on tank top', 'Wire to ESP32', 'Measure tank depth for calibration', 'Upload code', 'Test with known water levels'],
    working: 'HC-SR04 sends ultrasonic pulses and measures echo time to calculate distance to water surface. ESP32 converts this to tank fill percentage.',
    fieldLabels: ['Water Level (%)', 'Distance (cm)', 'Temperature (°C)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Light Intensity Logger',
    description: 'Log ambient light levels throughout the day using BH1750 digital light sensor. Useful for plant growth monitoring and energy studies.',
    type: ProjectType.IOT,
    category: 'Environment',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['ESP32', 'BH1750', 'Light', 'Logging'],
    components: ['ESP32', 'BH1750 Light Sensor', 'Breadboard', 'Jumper Wires'],
    connections: ['BH1750 SDA to GPIO21, SCL to GPIO22, VCC to 3.3V, GND to GND, ADDR to GND'],
    steps: ['Connect BH1750 via I2C', 'Install BH1750 library', 'Upload code', 'Place sensor in target location', 'Monitor light levels over time'],
    working: 'BH1750 provides direct digital output in lux. High resolution (1-65535 lux) makes it suitable for both indoor and outdoor light measurement.',
    fieldLabels: ['Light Intensity (lux)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Dew Point Calculator',
    description: 'Calculate dew point using temperature and humidity readings. Essential for agriculture and HVAC applications.',
    type: ProjectType.IOT,
    category: 'Weather Station',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2 hours',
    tags: ['ESP32', 'SHT31', 'Dew Point', 'Agriculture'],
    components: ['ESP32', 'SHT31-D Temperature/Humidity Sensor', 'OLED Display', 'Breadboard'],
    connections: ['SHT31 SDA to GPIO21, SCL to GPIO22, VCC to 3.3V'],
    steps: ['Wire SHT31 sensor', 'Connect OLED display', 'Install SHT31 library', 'Upload code with dew point calculation', 'Verify readings'],
    working: 'SHT31 provides accurate temperature and humidity. ESP32 calculates dew point using the Magnus formula and displays all three values.',
    fieldLabels: ['Temperature (°C)', 'Humidity (%)', 'Dew Point (°C)'],
    featured: false,
    isPublished: true,
  },

  // Home Automation (10)
  {
    title: 'Smart Home Temperature Control with Relay',
    description: 'Automate home heating/cooling using ESP32, temperature sensor, and relay module. Set target temperature and let it control your AC or heater.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'Relay', 'DS18B20', 'Automation', 'HVAC'],
    components: ['ESP32', 'DS18B20 Waterproof Temperature Sensor', '5V Relay Module', '10kΩ Resistor', 'Jumper Wires'],
    connections: ['DS18B20 data to GPIO4 with 10k pull-up to 3.3V', 'Relay IN to GPIO12, VCC to 5V, GND to GND'],
    steps: ['Wire DS18B20 sensor', 'Connect relay module', 'Install OneWire and DallasTemperature libraries', 'Upload code with target temperature', 'Connect appliance to relay', 'Test automatic switching'],
    working: 'DS18B20 provides waterproof temperature readings. ESP32 compares current temp with target and toggles relay to turn heating/cooling on or off.',
    fieldLabels: ['Temperature (°C)', 'Target Temp (°C)', 'Relay State'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'WiFi Smart Light Switch',
    description: 'Convert any regular light switch into a smart switch using ESP32 and relay. Control lights from your phone or automate schedules.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2-3 hours',
    tags: ['ESP32', 'Relay', 'Smart Switch', 'Lighting'],
    components: ['ESP32', '5V Relay Module', 'Push Button', 'Enclosure', 'AC-DC 5V Module'],
    connections: ['Push button to GPIO15, Relay IN to GPIO13', 'Wire relay in series with light switch'],
    steps: ['Wire ESP32 with relay and button', 'Install in switch box', 'Upload firmware', 'Configure WiFi', 'Test manual and remote control'],
    working: 'ESP32 maintains light state and responds to both physical button presses and remote API commands. Relay switches the AC mains safely.',
    fieldLabels: ['Light State', 'Power Consumption (W)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Door Lock with RFID',
    description: 'Build an RFID-based door lock system using ESP32 and RC522 reader. Log all entry attempts and control access remotely.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '4-5 hours',
    tags: ['ESP32', 'RC522', 'RFID', 'Door Lock', 'Security'],
    components: ['ESP32', 'RC522 RFID Module', 'RFID Cards/Tags', 'Servo Motor MG996R', 'Breadboard'],
    connections: ['RC522 MOSI to GPIO23, MISO to GPIO19, SCK to GPIO18, SDA to GPIO5, VCC to 3.3V', 'Servo signal to GPIO26'],
    steps: ['Wire RC522 RFID reader', 'Connect servo motor', 'Install MFRC522 library', 'Register authorized RFID tags', 'Upload code', 'Mount on door', 'Test access control'],
    working: 'RC522 reads RFID tag UID. ESP32 checks against authorized list and activates servo to unlock door. All access attempts are logged to Pulse.',
    fieldLabels: ['Access Granted', 'Tag ID', 'Attempt Count'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Motion-Activated Night Light',
    description: 'Create an energy-efficient night light that turns on automatically when motion is detected using PIR sensor and LED strip.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.BEGINNER,
    duration: '1 hour',
    tags: ['Arduino', 'PIR', 'LED', 'Motion', 'Energy Saving'],
    components: ['Arduino Nano', 'HC-SR501 PIR Sensor', 'LED Strip 5V', 'MOSFET Module', 'Jumper Wires'],
    connections: ['PIR OUT to D2, VCC to 5V, GND to GND', 'MOSFET gate to D9, LED strip to MOSFET drain'],
    steps: ['Connect PIR sensor', 'Wire LED strip through MOSFET', 'Upload code', 'Adjust PIR sensitivity and delay', 'Mount in hallway'],
    working: 'PIR sensor detects infrared radiation from moving bodies. Arduino turns on LED strip for a configurable duration after each detection.',
    fieldLabels: ['Motion Detected', 'Light On', 'Duration (min)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Curtain Controller',
    description: 'Automate your curtains using stepper motor and light sensor. Opens at sunrise, closes at sunset or based on room temperature.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.ADVANCED,
    duration: '6-8 hours',
    tags: ['ESP32', 'Stepper Motor', 'LDR', 'Automation'],
    components: ['ESP32', '28BYJ-48 Stepper Motor + ULN2003 Driver', 'LDR Module', 'BH1750 Light Sensor', 'Curtain Track'],
    connections: ['Stepper IN1-4 to GPIO12-15', 'LDR to A0, BH1750 to I2C'],
    steps: ['Mount stepper motor on curtain track', 'Wire motor driver to ESP32', 'Install light sensors', 'Upload code with sun position calculation', 'Calibrate open/close positions', 'Test automation'],
    working: 'ESP32 calculates sunrise/sunset times and uses light sensor readings to confirm. Stepper motor opens or closes curtains accordingly.',
    fieldLabels: ['Curtain Position (%)', 'Light Level (lux)', 'Room Temp (°C)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Voice-Controlled Home Assistant',
    description: 'Build a voice-controlled home automation hub using ESP32 and INMP441 microphone. Control devices with simple voice commands.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['ESP32', 'INMP441', 'Voice', 'I2S', 'AI'],
    components: ['ESP32', 'INMP441 MEMS Microphone', 'Relay Module x4', 'LED Indicator', 'Speaker Module'],
    connections: ['INMP441 SD to GPIO15, WS to GPIO14, SCK to GPIO32', 'Relays to GPIO25-28'],
    steps: ['Wire INMP441 via I2S', 'Connect relay modules', 'Install ESP-ADF or custom voice recognition', 'Train voice commands', 'Upload firmware', 'Test voice control'],
    working: 'ESP32 captures audio via I2S microphone, processes it with keyword spotting algorithm, and triggers corresponding relay actions.',
    fieldLabels: ['Voice Command', 'Device State', 'Confidence (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Power Strip with Energy Monitoring',
    description: 'Build a smart power strip that monitors energy consumption of each outlet and can be controlled remotely.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.ADVANCED,
    duration: '6-8 hours',
    tags: ['ESP32', 'PZEM-004T', 'Relay', 'Energy Monitor'],
    components: ['ESP32', 'PZEM-004T Energy Monitor', '4-Channel Relay Module', 'AC Sockets x4', 'Enclosure'],
    connections: ['PZEM-004T TX to GPIO16, RX to GPIO17', 'Relay channels to GPIO25-28'],
    steps: ['Wire PZEM-004T current transformer', 'Connect relay channels to outlets', 'Install PZEM library', 'Upload code', 'Calibrate energy readings', 'Test remote control'],
    working: 'PZEM-004T measures voltage, current, power, and energy for each outlet. ESP32 reads these values and allows remote on/off control via Pulse API.',
    fieldLabels: ['Voltage (V)', 'Current (A)', 'Power (W)', 'Energy (kWh)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Automated Plant Watering System',
    description: 'Keep your plants healthy with an automated watering system using soil moisture sensor, water pump, and ESP32 scheduling.',
    type: ProjectType.IOT,
    category: 'Smart Garden',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'Soil Moisture', 'Water Pump', 'Relay', 'Garden'],
    components: ['ESP32', 'Capacitive Soil Moisture Sensor', '5V Water Pump', 'Relay Module', 'Tubing', 'Water Container'],
    connections: ['Soil sensor to GPIO34', 'Relay IN to GPIO12, pump to relay COM/NO'],
    steps: ['Insert soil moisture sensor', 'Connect water pump through relay', 'Wire to ESP32', 'Set moisture thresholds', 'Upload code', 'Test watering cycle'],
    working: 'ESP32 monitors soil moisture continuously. When it drops below threshold, it activates the pump for a calculated duration based on soil dryness.',
    fieldLabels: ['Soil Moisture (%)', 'Pump Running', 'Water Volume (ml)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Thermostat with Touch Display',
    description: 'Build a wall-mounted smart thermostat with Nextion touch display, DHT22 sensor, and relay control for HVAC systems.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['ESP32', 'Nextion', 'DHT22', 'Thermostat', 'Touch'],
    components: ['ESP32', 'Nextion 3.5" Display', 'DHT22', 'Relay Module', 'DS3231 RTC Module', 'Enclosure'],
    connections: ['Nextion TX to GPIO16, RX to GPIO17', 'DHT22 to GPIO4, RTC to I2C', 'Relay to GPIO12'],
    steps: ['Design Nextion UI screens', 'Wire all components', 'Install libraries', 'Upload ESP32 firmware', 'Configure schedule program', 'Mount on wall', 'Connect to HVAC'],
    working: 'Nextion display provides touch interface for temperature settings and scheduling. ESP32 reads temperature and controls HVAC relay based on schedule and target temp.',
    fieldLabels: ['Room Temp (°C)', 'Target Temp (°C)', 'HVAC State', 'Humidity (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Garage Door Monitor & Alert',
    description: 'Monitor your garage door status with magnetic reed switch and get instant alerts when it is left open.',
    type: ProjectType.IOT,
    category: 'Home Automation',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['ESP32', 'Reed Switch', 'Magnet', 'Alerts', 'Security'],
    components: ['ESP32', 'Magnetic Reed Switch', 'Neodymium Magnet', 'Jumper Wires', 'Enclosure'],
    connections: ['Reed switch between GPIO34 and GND with internal pull-up enabled'],
    steps: ['Mount reed switch on door frame', 'Attach magnet to door', 'Wire to ESP32', 'Upload code', 'Configure alert threshold time', 'Test door open/close detection'],
    working: 'Reed switch closes when magnet is near (door closed). ESP32 monitors state and sends alert if door remains open beyond configured time.',
    fieldLabels: ['Door State', 'Open Duration (min)'],
    featured: false,
    isPublished: true,
  },

  // Health & Wearables (8)
  {
    title: 'Heart Rate Monitor with Pulse Oximeter',
    description: 'Build a wearable heart rate and blood oxygen monitor using MAX30102 sensor with OLED display and data logging.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'MAX30102', 'Heart Rate', 'SpO2', 'Health'],
    components: ['ESP32', 'MAX30102 Sensor', 'OLED Display', 'Battery Module', '3D Printed Case'],
    connections: ['MAX30102 SDA to GPIO21, SCL to GPIO22, INT to GPIO25', 'OLED to same I2C bus'],
    steps: ['Wire MAX30102 via I2C', 'Connect OLED display', 'Install MAX30102 library', 'Upload code', 'Calibrate with finger placement', 'Test heart rate accuracy'],
    working: 'MAX30102 uses photoplethysmography (PPG) with red and IR LEDs to measure blood volume changes. ESP32 calculates heart rate and SpO2 from the raw data.',
    fieldLabels: ['Heart Rate (BPM)', 'SpO2 (%)', 'Temperature (°C)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Body Temperature Logger',
    description: 'Continuous body temperature monitoring using MLX90614 non-contact IR sensor. Perfect for fever tracking and health monitoring.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.BEGINNER,
    duration: '2 hours',
    tags: ['Arduino', 'MLX90614', 'Temperature', 'Health', 'IR'],
    components: ['Arduino Nano', 'MLX90614 IR Temperature Sensor', 'OLED Display', 'Battery'],
    connections: ['MLX90614 SDA to A4, SCL to A5, VCC to 3.3V'],
    steps: ['Connect MLX90614 via I2C', 'Wire OLED display', 'Install library', 'Upload code', 'Test at different distances', 'Log data over time'],
    working: 'MLX90614 measures infrared radiation emitted by the body and converts it to temperature. Non-contact design allows hygienic repeated measurements.',
    fieldLabels: ['Body Temp (°C)', 'Ambient Temp (°C)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Pill Reminder Box',
    description: 'Never miss medication again. This smart pill box uses RTC for scheduling, buzzer for alerts, and logs adherence to the cloud.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '4-5 hours',
    tags: ['ESP32', 'DS3231', 'Buzzer', 'Health', 'RTC'],
    components: ['ESP32', 'DS3231 RTC Module', 'Buzzer', 'LEDs x4', 'Push Buttons x4', 'Pill Box'],
    connections: ['RTC to I2C', 'Buzzer to GPIO26', 'LEDs to GPIO12-15', 'Buttons to GPIO32-35'],
    steps: ['Wire RTC module', 'Connect LEDs for each pill compartment', 'Wire buttons and buzzer', 'Upload code with schedule', 'Set medication times', 'Test reminder flow'],
    working: 'DS3231 keeps accurate time. At scheduled times, ESP32 lights the correct compartment LED and sounds buzzer. Pressing the button confirms dose taken.',
    fieldLabels: ['Dose Taken', 'Missed Doses', 'Battery Level (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Posture Correction Wearable',
    description: 'Wearable device that detects poor posture using MPU6050 accelerometer/gyroscope and vibrates to remind you to sit straight.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'MPU6050', 'Vibration', 'Posture', 'Wearable'],
    components: ['ESP32', 'MPU6050 IMU Sensor', 'Vibration Motor', 'LiPo Battery', '3D Printed Case'],
    connections: ['MPU6050 SDA to GPIO21, SCL to GPIO22, INT to GPIO25', 'Vibration motor to GPIO26 via MOSFET'],
    steps: ['Wire MPU6050 via I2C', 'Connect vibration motor', 'Install MPU6050 library', 'Upload code', 'Calibrate good posture angle', 'Wear and test'],
    working: 'MPU6050 measures body tilt angles. When deviation from calibrated good posture exceeds threshold for more than 30 seconds, vibration motor activates.',
    fieldLabels: ['Tilt Angle (°)', 'Posture Score', 'Alerts Count'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Sleep Quality Monitor',
    description: 'Track sleep patterns using piezo vibration sensor under mattress. Analyzes sleep cycles and quality without wearing anything.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'Piezo', 'Sleep', 'Monitoring'],
    components: ['ESP32', 'Piezo Vibration Sensor', 'Op-Amp Module', 'SD Card Module', 'Enclosure'],
    connections: ['Piezo to op-amp input, op-amp output to GPIO34', 'SD card to SPI pins'],
    steps: ['Connect piezo sensor with op-amp', 'Wire to ESP32', 'Place under mattress', 'Upload code', 'Record baseline movement', 'Analyze sleep data'],
    working: 'Piezo sensor detects body movements during sleep. ESP32 classifies sleep stages based on movement frequency and duration, logging data for analysis.',
    fieldLabels: ['Movement Count', 'Sleep Score', 'Deep Sleep (hrs)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Hand Washing Timer',
    description: 'Promote proper hand hygiene with an automated 20-second timer using proximity sensor and LED progress indicator.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.BEGINNER,
    duration: '1 hour',
    tags: ['Arduino', 'IR Sensor', 'LED', 'Hygiene'],
    components: ['Arduino Nano', 'IR Proximity Sensor', 'WS2812B LED Ring', 'Buzzer'],
    connections: ['IR sensor to D2', 'WS2812B data to D6', 'Buzzer to D9'],
    steps: ['Wire IR proximity sensor', 'Connect LED ring', 'Upload code', 'Mount near sink', 'Test hand detection'],
    working: 'IR sensor detects hands under faucet. Arduino starts 20-second countdown with LED ring progress indicator and plays a tune when complete.',
    fieldLabels: ['Wash Count', 'Avg Duration (s)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Blood Pressure Estimator',
    description: 'Estimate blood pressure trends using pulse wave velocity measurement with two PPG sensors at different body points.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.ADVANCED,
    duration: '6-8 hours',
    tags: ['ESP32', 'MAX30102', 'PPG', 'Blood Pressure'],
    components: ['ESP32', 'MAX30102 x2', 'OLED Display', 'Battery'],
    connections: ['Both MAX30102 on separate I2C buses using multiplexer'],
    steps: ['Wire two MAX30102 sensors', 'Install libraries', 'Upload code with PTT calculation', 'Place sensors on finger and ear', 'Calibrate with cuff measurement', 'Track trends over time'],
    working: 'Measures Pulse Transit Time (PTT) between two body points. Blood pressure is estimated using the relationship between PTT and arterial stiffness.',
    fieldLabels: ['Systolic (mmHg)', 'Diastolic (mmHg)', 'Heart Rate (BPM)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'UV Exposure Tracker',
    description: 'Wearable UV exposure tracker that monitors cumulative UV dose and alerts when you should reapply sunscreen.',
    type: ProjectType.IOT,
    category: 'Health',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2-3 hours',
    tags: ['ESP32', 'VEML6075', 'UV', 'Wearable'],
    components: ['ESP32', 'VEML6075 UV Sensor', 'OLED Display', 'Coin Cell Battery', 'Wristband'],
    connections: ['VEML6075 SDA to GPIO21, SCL to GPIO22'],
    steps: ['Wire UV sensor', 'Connect display', 'Upload code with UV dose calculation', 'Mount on wristband', 'Test in sunlight', 'Set skin type parameters'],
    working: 'VEML6075 measures UV intensity in real-time. ESP32 calculates cumulative UV dose based on skin type settings and alerts when safe exposure limit is reached.',
    fieldLabels: ['UV Index', 'Cumulative Dose', 'Time to Reapply (min)'],
    featured: false,
    isPublished: true,
  },

  // Robotics & Motors (7)
  {
    title: 'ESP32 Line Following Robot',
    description: 'Build a line following robot using ESP32 and IR sensor array. Features PID control for smooth tracking and obstacle avoidance.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '5-6 hours',
    tags: ['ESP32', 'IR Sensors', 'Motors', 'PID', 'Robot'],
    components: ['ESP32', '5-Channel IR Line Sensor', 'L298N Motor Driver', 'DC Motors x2', 'Robot Chassis', 'Wheels'],
    connections: ['IR sensors to GPIO32-36', 'L298N IN1-4 to GPIO25-28', 'Motor enable to GPIO12-13'],
    steps: ['Assemble robot chassis', 'Mount IR sensor array', 'Wire motor driver', 'Install motor control library', 'Upload PID line following code', 'Test on black line', 'Tune PID parameters'],
    working: 'IR sensors detect line position. ESP32 calculates error and applies PID control to adjust motor speeds, keeping the robot centered on the line.',
    fieldLabels: ['Line Position', 'Left Speed', 'Right Speed', 'Error'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Robotic Arm Controller',
    description: 'Control a 4-DOF robotic arm using ESP32 and PCA9685 servo driver. Program movements and automate repetitive tasks.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['ESP32', 'PCA9685', 'Servo', 'Robot Arm', 'Automation'],
    components: ['ESP32', 'PCA9685 16-Channel Servo Driver', 'MG996R Servos x4', 'Robot Arm Kit', 'Joystick Module'],
    connections: ['PCA9685 SDA to GPIO21, SCL to GPIO22', 'Servos to PCA9685 channels 0-3', 'Joystick to GPIO34-35'],
    steps: ['Assemble robotic arm', 'Wire PCA9685 servo driver', 'Connect servos', 'Attach joystick', 'Upload control code', 'Calibrate servo ranges', 'Test movement sequences'],
    working: 'PCA9685 provides precise PWM control for multiple servos via I2C. ESP32 reads joystick input and translates to arm joint angles using inverse kinematics.',
    fieldLabels: ['Joint 1 (°)', 'Joint 2 (°)', 'Joint 3 (°)', 'Grip State'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Self-Balancing Robot',
    description: 'Build a two-wheeled self-balancing robot using MPU6050 IMU and PID control. A classic robotics project that teaches control theory.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['Arduino', 'MPU6050', 'PID', 'Balancing', 'Robot'],
    components: ['Arduino Nano', 'MPU6050 IMU', 'L298N Motor Driver', 'NEMA 17 Stepper Motors x2', 'Robot Frame', 'Battery'],
    connections: ['MPU6050 to I2C', 'L298N IN1-4 to D5-D8', 'Motor outputs to stepper motors'],
    steps: ['Build robot frame', 'Mount MPU6050 at center of gravity', 'Wire motor driver', 'Install PID and MPU libraries', 'Upload balancing code', 'Tune PID gains', 'Test balance'],
    working: 'MPU6050 provides tilt angle. PID controller calculates required motor correction to maintain balance. Stepper motors provide precise torque control.',
    fieldLabels: ['Tilt Angle (°)', 'Motor Speed', 'PID Output', 'Battery (V)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'WiFi Controlled Rover',
    description: 'Build a WiFi-controlled rover car with camera streaming using ESP32-CAM. Drive it remotely from your browser.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '4-5 hours',
    tags: ['ESP32-CAM', 'Camera', 'Robot', 'WiFi', 'Streaming'],
    components: ['ESP32-CAM Module', 'L298N Motor Driver', 'DC Motors x2', 'Robot Chassis', 'Battery 18650 x2', 'FTDI Programmer'],
    connections: ['L298N IN1-4 to GPIO12-14, GPIO4', 'Motors to L298N outputs', 'Power from battery pack'],
    steps: ['Assemble rover chassis', 'Wire motor driver to ESP32-CAM', 'Program using FTDI adapter', 'Upload camera web server code', 'Connect via browser', 'Add motor control to web interface'],
    working: 'ESP32-CAM streams video over WiFi while also controlling motors. Web interface shows live video feed with directional controls overlaid.',
    fieldLabels: ['Speed', 'Direction', 'Battery (V)', 'Signal Strength'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Automated Pet Feeder',
    description: 'Build a timed automatic pet feeder using servo motor and RTC module. Schedule feeding times and portion sizes remotely.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '4-5 hours',
    tags: ['ESP32', 'Servo', 'RTC', 'Pet', 'Automation'],
    components: ['ESP32', 'DS3231 RTC', 'SG90 Servo', 'Food Container', '3D Printed Dispenser', 'Buzzer'],
    connections: ['RTC to I2C', 'Servo signal to GPIO26', 'Buzzer to GPIO25'],
    steps: ['3D print or build food dispenser mechanism', 'Mount servo on dispenser', 'Wire RTC and buzzer', 'Upload code with feeding schedule', 'Fill with pet food', 'Test dispensing mechanism'],
    working: 'RTC triggers feeding at scheduled times. Servo rotates to open food dispenser for a calibrated duration, releasing the correct portion size.',
    fieldLabels: ['Feedings Today', 'Portion (g)', 'Food Level (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'CNC Plotter Machine',
    description: 'Build a small CNC plotter using DVD drive stepper motors and Arduino. Draw vector graphics from your computer.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.ADVANCED,
    duration: '8-10 hours',
    tags: ['Arduino', 'Stepper Motors', 'CNC', 'GRBL', 'Plotter'],
    components: ['Arduino Uno', 'CNC Shield', 'A4988 Stepper Drivers x2', 'DVD Drive Steppers x2', 'Servo for Pen', 'Frame Materials'],
    connections: ['CNC shield on Arduino', 'Steppers to X and Y axis', 'Pen servo to Z axis'],
    steps: ['Build XY frame from DVD drives', 'Mount CNC shield and drivers', 'Wire stepper motors', 'Install GRBL firmware', 'Connect to computer', 'Send G-code commands', 'Test drawing'],
    working: 'GRBL firmware on Arduino interprets G-code commands and controls stepper motors for precise XY positioning. Servo lifts/lowers the pen.',
    fieldLabels: ['X Position (mm)', 'Y Position (mm)', 'Pen State', 'Speed (mm/min)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Obstacle Avoiding Robot',
    description: 'Build an autonomous robot that navigates and avoids obstacles using ultrasonic sensor and servo scanning.',
    type: ProjectType.IOT,
    category: 'Robotics',
    difficulty: Difficulty.BEGINNER,
    duration: '3-4 hours',
    tags: ['Arduino', 'HC-SR04', 'Servo', 'Robot', 'Autonomous'],
    components: ['Arduino Uno', 'HC-SR04 Ultrasonic Sensor', 'SG90 Servo', 'L298N Motor Driver', 'Robot Chassis', 'DC Motors x2'],
    connections: ['HC-SR04 Trig to D9, Echo to D10', 'Servo to D6', 'L298N IN1-4 to D2-D5'],
    steps: ['Assemble robot chassis', 'Mount ultrasonic sensor on servo', 'Wire motor driver', 'Upload obstacle avoidance code', 'Test in open space', 'Adjust detection distance'],
    working: 'Ultrasonic sensor scans for obstacles by rotating on servo. When obstacle is detected within threshold, Arduino stops, scans for clear path, and turns accordingly.',
    fieldLabels: ['Front Distance (cm)', 'Left Distance (cm)', 'Right Distance (cm)', 'Speed'],
    featured: false,
    isPublished: true,
  },

  // Security & Monitoring (8)
  {
    title: 'ESP32-CAM Security Camera',
    description: 'Build a WiFi security camera with motion detection using ESP32-CAM. Capture photos and stream video to your phone.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32-CAM', 'Camera', 'Motion Detection', 'Security', 'WiFi'],
    components: ['ESP32-CAM Module', 'FTDI Programmer', 'Micro SD Card', 'PIR Sensor', 'Enclosure', '5V Power Supply'],
    connections: ['PIR OUT to GPIO13', 'SD card to ESP32-CAM built-in slot'],
    steps: ['Flash ESP32-CAM firmware using FTDI', 'Connect PIR sensor', 'Insert SD card', 'Configure WiFi', 'Set up motion detection', 'Mount in enclosure', 'Test streaming and capture'],
    working: 'ESP32-CAM streams video over HTTP. PIR sensor triggers photo capture and saves to SD card. Images can also be uploaded to Pulse via API.',
    fieldLabels: ['Motion Detected', 'Photos Captured', 'Storage Used (%)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Smart Doorbell with Notification',
    description: 'Create a smart doorbell that sends push notifications and captures visitor photos when someone rings.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'Camera', 'Doorbell', 'Notification'],
    components: ['ESP32-CAM', 'Push Button', 'Buzzer', 'LED', 'Enclosure', 'Power Supply'],
    connections: ['Button to GPIO4 with pull-up', 'Buzzer to GPIO2', 'LED to GPIO3'],
    steps: ['Wire push button as doorbell', 'Connect buzzer and LED', 'Upload ESP32-CAM code', 'Configure notification service', 'Mount at door', 'Test doorbell press'],
    working: 'When button is pressed, ESP32-CAM captures photo, sounds buzzer, and sends notification with image to Pulse dashboard.',
    fieldLabels: ['Ring Count', 'Last Ring Time', 'Battery Level (%)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Gas Leak Detector & Alarm',
    description: 'Detect LPG, propane, and natural gas leaks using MQ-5 sensor with loud alarm and remote notification.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['Arduino', 'MQ-5', 'Gas', 'Alarm', 'Safety'],
    components: ['Arduino Uno', 'MQ-5 Gas Sensor', 'Buzzer', 'LED', 'Relay Module'],
    connections: ['MQ-5 AOUT to A0, DOUT to D2', 'Buzzer to D8', 'Relay to D9'],
    steps: ['Connect MQ-5 sensor', 'Wire buzzer and relay', 'Upload code', 'Calibrate in clean air', 'Test with gas source', 'Set alarm threshold'],
    working: 'MQ-5 detects combustible gases. When concentration exceeds safe threshold, Arduino triggers buzzer alarm and relay to activate exhaust fan.',
    fieldLabels: ['Gas Level (ppm)', 'Alarm State', 'Sensor Status'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Window Break Detector',
    description: 'Detect glass breakage using piezo sensor and vibration analysis. Perfect for home security systems.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2-3 hours',
    tags: ['ESP32', 'Piezo', 'Security', 'Glass Break'],
    components: ['ESP32', 'Piezo Sensor', 'Op-Amp Module', 'Buzzer', 'LED'],
    connections: ['Piezo to op-amp input, output to GPIO34', 'Buzzer to GPIO26'],
    steps: ['Connect piezo with op-amp circuit', 'Wire buzzer and LED', 'Upload code with frequency analysis', 'Mount on window glass', 'Test with glass tap', 'Tune detection threshold'],
    working: 'Piezo sensor detects vibrations. ESP32 analyzes frequency spectrum to distinguish glass break pattern from normal vibrations.',
    fieldLabels: ['Vibration Level', 'Break Detected', 'Alert Count'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Flood Detection System',
    description: 'Early flood warning system using water level sensors. Detects water presence and sends immediate alerts.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['ESP32', 'Water Sensor', 'Flood', 'Alerts'],
    components: ['ESP32', 'Water Level Sensor', 'Buzzer', 'LED', 'Enclosure'],
    connections: ['Water sensor AOUT to GPIO34, DOUT to GPIO35', 'Buzzer to GPIO26'],
    steps: ['Place water sensor at lowest point', 'Wire to ESP32', 'Upload code', 'Test with water', 'Set alert thresholds', 'Mount in basement or utility room'],
    working: 'Water sensor detects presence of water. ESP32 triggers alarm and sends alert through Pulse when water level exceeds threshold.',
    fieldLabels: ['Water Level', 'Flood Alert', 'Sensor Status'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Perimeter Laser Tripwire',
    description: 'Build an invisible security tripwire using laser diode and LDR. Detects intrusions across doorways or windows.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['Arduino', 'Laser', 'LDR', 'Tripwire', 'Security'],
    components: ['Arduino Nano', 'Laser Diode Module', 'LDR Sensor', 'Buzzer', 'LED'],
    connections: ['LDR to A0 with 10k pull-down', 'Buzzer to D8', 'Laser to D9 (always on)'],
    steps: ['Position laser diode across doorway', 'Place LDR to receive laser beam', 'Wire to Arduino', 'Upload code', 'Align laser beam', 'Test beam interruption'],
    working: 'LDR receives continuous laser light. When beam is interrupted, resistance changes dramatically. Arduino detects this and triggers alarm.',
    fieldLabels: ['Beam Status', 'Trip Count', 'Last Trigger'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smoke & Fire Detector',
    description: 'Detect smoke and fire using MQ-2 sensor and flame sensor. Dual detection for reliable fire alarm system.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.BEGINNER,
    duration: '1-2 hours',
    tags: ['Arduino', 'MQ-2', 'Flame Sensor', 'Fire', 'Safety'],
    components: ['Arduino Uno', 'MQ-2 Smoke Sensor', 'Flame Sensor Module', 'Buzzer', 'LED'],
    connections: ['MQ-2 AOUT to A0', 'Flame sensor DO to D2', 'Buzzer to D8'],
    steps: ['Connect MQ-2 sensor', 'Wire flame sensor', 'Connect buzzer', 'Upload code', 'Test with smoke source', 'Test with flame (safely)'],
    working: 'MQ-2 detects smoke particles while flame sensor detects IR radiation from flames. Either trigger activates the alarm for comprehensive fire detection.',
    fieldLabels: ['Smoke Level', 'Flame Detected', 'Alarm State'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Safe with Keypad Lock',
    description: 'Build a digital safe with keypad entry, servo lock mechanism, and tamper detection logging.',
    type: ProjectType.IOT,
    category: 'Security',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '4-5 hours',
    tags: ['Arduino', 'Keypad', 'Servo', 'Safe', 'Lock'],
    components: ['Arduino Uno', '4x4 Membrane Keypad', 'SG90 Servo', 'LCD Display 16x2', 'Safe Box', 'LED'],
    connections: ['Keypad rows/cols to D2-D9', 'Servo to D10', 'LCD to I2C', 'LED to D11'],
    steps: ['Wire keypad to Arduino', 'Connect LCD display', 'Mount servo as lock mechanism', 'Upload code with PIN management', 'Set master PIN', 'Test lock/unlock', 'Add tamper detection'],
    working: 'User enters PIN on keypad. Arduino validates against stored PIN and activates servo to unlock. Failed attempts are logged and trigger alert after 3 tries.',
    fieldLabels: ['Lock State', 'Failed Attempts', 'Last Access'],
    featured: false,
    isPublished: true,
  },

  // Energy & Power (7)
  {
    title: 'Solar Panel Power Monitor',
    description: 'Monitor your solar panel output in real-time. Track voltage, current, power generation, and daily energy yield.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'INA219', 'Solar', 'Power Monitor', 'Energy'],
    components: ['ESP32', 'INA219 Current/Voltage Sensor', 'OLED Display', 'Solar Panel', 'Jumper Wires'],
    connections: ['INA219 SDA to GPIO21, SCL to GPIO22, VCC to 3.3V', 'Solar panel + to INA219 Vin+, - to Vin-'],
    steps: ['Wire INA219 in series with solar panel', 'Connect OLED display', 'Install INA219 library', 'Upload code', 'Place solar panel in sunlight', 'Monitor power output'],
    working: 'INA219 measures bus voltage and current through shunt resistor. ESP32 calculates power and integrates over time for energy yield.',
    fieldLabels: ['Voltage (V)', 'Current (A)', 'Power (W)', 'Daily Energy (Wh)'],
    featured: true,
    isPublished: true,
  },
  {
    title: 'Battery Capacity Tester',
    description: 'Test and measure the actual capacity of Li-ion and LiPo batteries using electronic load and precise current measurement.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['Arduino', 'INA219', 'Battery', 'Testing'],
    components: ['Arduino Uno', 'INA219 Sensor', 'Power Resistor 10Ω 10W', 'OLED Display', 'Battery Holder'],
    connections: ['INA219 to I2C', 'Resistor as load across battery through INA219'],
    steps: ['Wire INA219 in series with load resistor', 'Connect OLED', 'Upload code with capacity calculation', 'Insert battery to test', 'Monitor discharge curve', 'Calculate actual capacity'],
    working: 'INA219 measures discharge current. Arduino integrates current over time until battery reaches cutoff voltage, calculating total capacity in mAh.',
    fieldLabels: ['Voltage (V)', 'Current (mA)', 'Capacity (mAh)', 'Temperature (°C)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Energy Consumption Monitor for Home',
    description: 'Monitor your home energy consumption using SCT-013 non-invasive current transformer. Track usage per circuit.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.ADVANCED,
    duration: '5-6 hours',
    tags: ['ESP32', 'SCT-013', 'Energy', 'Current Transformer', 'Home'],
    components: ['ESP32', 'SCT-013-030 Current Transformer', 'ADS1115 ADC Module', 'OLED Display', 'Burden Resistor'],
    connections: ['SCT-013 to burden resistor, voltage across resistor to ADS1115 A0', 'ADS1115 to I2C'],
    steps: ['Clamp SCT-013 around live wire', 'Wire burden resistor and ADS1115', 'Connect OLED', 'Upload code with RMS calculation', 'Calibrate with known load', 'Monitor consumption'],
    working: 'SCT-013 induces current proportional to AC line current. ADS1115 digitizes the AC waveform. ESP32 calculates RMS current and power.',
    fieldLabels: ['Current (A)', 'Power (W)', 'Daily Usage (kWh)', 'Cost ($)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Wind Turbine Power Monitor',
    description: 'Monitor a small wind turbine output. Track RPM, voltage, current, and calculate power coefficient.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '3-4 hours',
    tags: ['ESP32', 'INA219', 'Hall Effect', 'Wind Turbine'],
    components: ['ESP32', 'INA219', 'A3144 Hall Effect Sensor', 'Magnet', 'OLED Display'],
    connections: ['INA219 to I2C', 'Hall sensor to GPIO14', 'Magnet on turbine blade'],
    steps: ['Mount hall sensor near turbine', 'Attach magnet to blade', 'Wire INA219 to turbine output', 'Connect OLED', 'Upload code', 'Test in wind', 'Calculate efficiency'],
    working: 'Hall sensor counts blade rotations for RPM. INA219 measures electrical output. ESP32 calculates power coefficient and logs performance data.',
    fieldLabels: ['RPM', 'Voltage (V)', 'Current (A)', 'Power (W)'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'Smart Power Bank Monitor',
    description: 'Add smart monitoring to any power bank. Track charge/discharge cycles, capacity, and health over time.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.BEGINNER,
    duration: '2 hours',
    tags: ['ESP32', 'INA219', 'Power Bank', 'Battery'],
    components: ['ESP32', 'INA219 Sensor', 'OLED Display', 'USB Breakout Board'],
    connections: ['INA219 in series with USB output', 'OLED to I2C'],
    steps: ['Wire INA219 between battery and USB output', 'Connect OLED', 'Upload code', 'Test with phone charging', 'Monitor discharge curve'],
    working: 'INA219 monitors current flow in and out of power bank. ESP32 tracks total energy delivered, charge cycles, and estimates battery health.',
    fieldLabels: ['Voltage (V)', 'Current (A)', 'Remaining (%)', 'Cycles'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'AC Mains Voltage Monitor',
    description: 'Monitor AC mains voltage safely using ZMPT101B voltage transformer module. Detect power outages and voltage fluctuations.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.INTERMEDIATE,
    duration: '2-3 hours',
    tags: ['ESP32', 'ZMPT101B', 'AC Voltage', 'Mains', 'Monitoring'],
    components: ['ESP32', 'ZMPT101B AC Voltage Sensor', 'OLED Display', 'Enclosure'],
    connections: ['ZMPT101B OUT to GPIO34, VCC to 5V, GND to GND'],
    steps: ['Connect ZMPT101B to AC mains (carefully!)', 'Wire output to ESP32', 'Upload code with RMS calculation', 'Calibrate with multimeter', 'Test voltage monitoring', 'Set over/under voltage alerts'],
    working: 'ZMPT101B provides isolated AC voltage measurement. ESP32 samples the waveform and calculates RMS voltage, detecting outages and fluctuations.',
    fieldLabels: ['AC Voltage (V)', 'Frequency (Hz)', 'Power State'],
    featured: false,
    isPublished: true,
  },
  {
    title: 'UPS Battery Monitor',
    description: 'Monitor your UPS battery health including voltage, temperature, and estimated backup time remaining.',
    type: ProjectType.IOT,
    category: 'Energy',
    difficulty: Difficulty.BEGINNER,
    duration: '2 hours',
    tags: ['Arduino', 'Voltage Divider', 'DS18B20', 'UPS', 'Battery'],
    components: ['Arduino Nano', 'Voltage Divider Resistors', 'DS18B20 Temperature Sensor', 'OLED Display'],
    connections: ['Voltage divider output to A0', 'DS18B20 to D2 with 4.7k pull-up'],
    steps: ['Build voltage divider for battery voltage', 'Wire temperature sensor to battery', 'Connect OLED', 'Upload code', 'Calibrate voltage reading', 'Monitor battery health'],
    working: 'Voltage divider scales battery voltage to Arduino ADC range. Temperature sensor monitors battery temp. Arduino estimates backup time based on load and capacity.',
    fieldLabels: ['Battery Voltage (V)', 'Temperature (°C)', 'Backup Time (min)', 'Health (%)'],
    featured: false,
    isPublished: true,
  },
]

async function main() {
  console.log('🌱 Seeding database...')

  // Create a demo user
  const hashedPassword = await bcrypt.hash('demo1234', 10)

  let user = await prisma.user.findFirst({
    where: { email: 'demo@pulse.io' }
  })

  if (!user) {
    user = await prisma.user.create({
      data: {
        email: 'demo@pulse.io',
        name: 'Demo User',
        password: hashedPassword,
        role: 'ADMIN',
      }
    })
    console.log('✅ Created demo user')
  } else {
    console.log('ℹ️  Demo user already exists')
  }

  // Clear existing projects
  await prisma.project.deleteMany({})
  console.log('🗑️  Cleared existing projects')

  // Seed projects
  for (const project of projects) {
    await prisma.project.create({
      data: {
        ...project,
        userId: user.id,
        references: [
          'https://docs.pulse.io',
          'https://github.com/pulse-iot',
        ],
        driveLink: 'https://drive.google.com/pulse-projects',
        imageUrl: `/images/projects/${project.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.jpg`,
      }
    })
    console.log(`✅ Created: ${project.title}`)
  }

  console.log(`\n🎉 Seeded ${projects.length} projects successfully!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
