import { PrismaClient, Difficulty, ProjectType } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const projects = [
  {
    title: "Simple Electric Circuit with Switch",
    description: "This project shows how a basic electric circuit works. By using a switch, students can turn an LED ON and OFF, just like controlling a light bulb at home.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["Switch one terminal → Battery Positive (+)", "Switch other terminal → Resistor → LED Anode (+)", "LED Cathode (–) → Battery Negative (–)"],
    connections: ["LED (Light Emitting Diode) – for output", "Switch / Push Button – to control the LED", "Battery (9V or AA battery pack) – as power source"],
    steps: ["Connect the battery, LED, resistor, and switch as per the circuit.", "Keep the switch in the OFF position → LED stays OFF.", "Press the switch → current flows → LED glows.", "Release the switch → current stops → LED goes OFF.", "Conclusion: (Predefined/self-written)", "This project helps students understand the fundamentals of electricity – how a switch controls the flow of current. It is a foundation for all electronic projects, from simple lamps to smart devices."],
    working: "The project works on the principle of a closed and open circuit.\nWhen the switch is pressed → circuit is closed → current flows → LED turns ON.\nWhen the switch is released → circuit is open → no current → LED turns OFF.",
    references: ["[1] Arduino, “Digital Read Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalread/. [Accessed: 27-Aug-2025].", "[2] All About Circuits, “Understanding LED Circuits,” Allaboutcircuits.com, 2022. [Online]. Available: https://www.allaboutcircuits.com/projects/introduction-to-leds/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(1)Simple%20Electric%20Circuit%20with%20Switch.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Basic Logic Gate Simulation (AND Gate)",
    description: "A simple project to simulate basic logic gates (AND, OR) using switches as inputs and LEDs as outputs. This project helps in understanding how digital logic gates work in practical hardware form.",
    type: ProjectType.BASIC,
    category: "Digital Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["Arduino UNO (or compatible) – microcontroller board", "2 x LEDs – for inputs", "1 x LEDs (Red/Green) – for AND output", "2 x 220Ω resistors – current limiting for LEDs", "2 x 10kΩ resistors – pull-down resistors for switches", "Breadboard – for assembling circuit", "Jumper Wires – for connections", "USB Cable / 5V Power Supply – to power Arduino"],
    connections: ["LED 1 → Digital Input Pin 2 on Arduino", "LED 2 → Digital Input Pin 3 on Arduino", "Resistors (10kΩ pull-down) → connected to each switch input", "LED (for AND gate output) → Digital Pin 7 (with 220Ω resistor)", "Power Supply → USB cable or external 5V supply for Arduino"],
    steps: ["Power ON the Arduino using USB or battery.", "Switches are used as inputs (0 = OFF, 1 = ON).", "Arduino reads the digital state of both switches.", "For AND Gate: LED glows only when both switches are ON.", "For OR Gate: LED glows when any one or both switches are ON.", "This demonstrates the basic working of logic gates."],
    working: "The switches represent binary inputs (0 or 1). The Arduino reads the switch states and computes the AND logic in software. Depending on the logic result, the respective LED (AND or OR) lights up.",
    references: ["[1] Arduino, “Arduino Digital Read Documentation,” Arduino.cc, [Online]. Available: https://www.arduino.cc/en/Reference/DigitalRead. [Accessed: 12-Sep-2025].", "[2] Electronics Tutorials, “Logic Gates Tutorial,” Electronicstutorials.ws, [Online]. Available: https://www.electronics-tutorials.ws/logic/logic_1.html. [Accessed: 12-Sep-2025]."],
    driveLink: "/word-files/(10)Basic_Logic_Gate_Simulation_AND%20Gate.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Basic Logic Gate Simulation (OR Gate)",
    description: "A simple project to simulate basic logic gates ( OR) using switches as inputs and LEDs as outputs. This project helps in understanding how digital logic gates work in practical hardware form.",
    type: ProjectType.BASIC,
    category: "Digital Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["Arduino UNO (or compatible) – microcontroller board", "2 x LED’s – for inputs", "1 x LEDs (Red/Green) – for OR outputs", "1 x 220Ω resistors – current limiting for LEDs", "2 x 10kΩ resistors – pull-down resistors for switches", "Breadboard – for assembling circuit", "Jumper Wires – for connections", "USB Cable / 5V Power Supply – to power Arduino"],
    connections: ["LED 1 → Digital Input Pin 2 on Arduino", "LED 2 → Digital Input Pin 3 on Arduino", "Resistors (10kΩ pull-down) → connected to each switch input", "LED (for OR gate output) → Digital Pin 7 (with 220Ω resistor)", "Power Supply → USB cable or external 5V supply for Arduino"],
    steps: ["Power ON the Arduino using USB or battery.", "Switches are used as inputs (0 = OFF, 1 = ON).", "Arduino reads the digital state of both switches.", "For AND Gate: LED glows only when both switches are ON.", "For OR Gate: LED glows when any one or both switches are ON.", "This demonstrates the basic working of logic gates."],
    working: "The switches represent binary inputs (0 or 1). The Arduino reads the switch states and computes the AND and OR logic in software. Depending on the logic result, the respective LED (AND or OR) lights up.",
    references: ["[1] Arduino, “Arduino Digital Read Documentation,” Arduino.cc, [Online]. Available: https://www.arduino.cc/en/Reference/DigitalRead. [Accessed: 12-Sep-2025].", "[2] Electronics Tutorials, “Logic Gates Tutorial,” Electronicstutorials.ws, [Online]. Available: https://www.electronics-tutorials.ws/logic/logic_1.html. [Accessed: 12-Sep-2025]."],
    driveLink: "/word-files/(11)Basic_Logic_Gate_Simulation_OR%20Gate.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Voice Controlled LED",
    description: "A toy that responds to claps or loud sounds using a sound sensor module and Arduino.",
    type: ProjectType.BASIC,
    category: "Input Devices",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Arduino", "LED", "Sensor"],
    components: ["Arduino UNO", "Sound Sensor Module", "LED", "Resistors", "Breadboard", "Jumper wires"],
    connections: ["Sound Sensor Module → Arduino D2", "LED → Arduino D8/D9"],
    steps: ["Connect sound sensor to Arduino.", "Upload sound-detection code.", "On clap, toy activates motor/LED/buzzer."],
    working: "When sound sensor detects a loud clap, Arduino triggers a toy action such as moving a motor, lighting an LED, or buzzing.",
    references: ["[1] Arduino Project Hub, 'Sound Sensor Tutorial'"],
    driveLink: "/word-files/(12)Voice_Controlled_Led.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Rain Alarm System",
    description: "An electronic alarm system that detects rain using a rain sensor or metal plate electrodes and alerts via buzzer/LED.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED", "Sensor", "Buzzer"],
    components: ["Arduino UNO", "Rain Sensor Module or DIY rain detector plate", "Buzzer", "220Ω Resistor", "Jumper wires", "Breadboard"],
    connections: ["Rain Sensor Module/Metal Plate → Digital Input D2 on Arduino", "Buzzer → Digital Pin 8"],
    steps: ["Power ON the Arduino.", "Rain sensor detects rain drops.", "Arduino reads input from sensor.", "If rain detected → buzzer sounds."],
    working: "When raindrops fall on the sensor plate, resistance changes, Arduino detects it and triggers buzzer/LED alarm.",
    references: ["[1] Arduino Project Hub, 'Rain Sensor Module Tutorial,' https://projecthub.arduino.cc"],
    driveLink: "/word-files/(13)Rain_Alarm_System.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Simple LED Blink using Esp32",
    description: "The Simple LED Blink project using ESP32 is a basic embedded systems project used to understand digital output control with a Wi-Fi enabled microcontroller.In this project, an LED is connected to an ESP32 board and programmed to turn ON and OFF at a fixed time interval.This project helps beginners understand GPIO pin control, delay functions, and basic ESP32 programming using the Arduino IDE.",
    type: ProjectType.IOT,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["ESP32", "Arduino", "LED"],
    components: ["ESP32 Development Board1 x LED1 x 220Ω ResistorJumper wiresBreadboard"],
    connections: ["ESP32 GPIO 2 → LED (with 220Ω resistor)LED Cathode → GNDPower supply: 5V (from USB) or 3.3V (ESP32 onboard)"],
    steps: ["Connect the LED to the ESP32 as per the circuit diagram.", "Connect the ESP32 to the computer using a USB cable.", "Select the ESP32 board and COM port in the Arduino IDE.", "Upload the LED blink program to the ESP32.", "Power ON the ESP32.", "The LED turns ON for a fixed duration.", "After the delay, the LED turns OFF automatically.", "This cycle repeats continuously."],
    working: "The ESP32 sends a HIGH signal (3.3V) to the GPIO pin, allowing current to flow and turn the LED ON.When the signal is LOW (0V), the current stops and the LED turns OFF.The ON and OFF timing is controlled using delay functions in the program.",
    references: ["[1] Espressif Systems, “ESP32 GPIO Control,” Espressif Documentation.[2] Arduino, “Digital Write Function,” Arduino.cc."],
    driveLink: "/word-files/(14)%20Led%20blink%20using%20esp32.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Water Detector",
    description: "The Water Detector is a simple project that helps in monitoring the full water level in a tank.It uses water sensor to detect water presence. When the water touches the sensor, the Arduino turns ON buzzer to alert the user. This prevents water overflow and dry running of motors.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "Sensor", "Buzzer", "Motor"],
    components: ["Arduino Uno / Nano", "Water sensor", "2 x LED (with 220Ω resistor)", "1 x Buzzer", "Jumper wires", "Breadboard"],
    connections: ["Arduino Pin A0 → water sensor", "Arduino Pin 10 → Buzzer", "Arduino Pin 8,9 → Led", "Power supply: 5V (from Arduino USB or adapter)"],
    steps: ["Insert water sensor at the desired level inside the water tank.", "Upload the Arduino code to the board.", "Connect the components as per the pinout.", "Power ON the system.", "When water touches the probes → LED glows and buzzer beeps.", "When water level drops → alert stops automatically."],
    working: "The project works on the principle of water conductivity.When water touches the water sensor, a small current passes through it.Arduino detects this as an input signal.\nIf tank is full → Green LED and Buzzer turn ON.\nIf no water is detected → Red led indicate the tank is empty.",
    references: ["[1] Arduino, “Digital Read Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalread/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(15)Water%20Detector.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Flame Detector",
    description: "The Flame Detector project using Arduino is designed to detect the presence of fire or flame and provide an alert.In this project, a flame sensor module is interfaced with an Arduino board to sense infrared radiation emitted by flames.When a flame is detected, the system activates an alert device such as an LED or buzzer.This project is useful for basic fire safety and monitoring applications.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "LED", "Sensor", "Buzzer"],
    components: ["Arduino Uno / NanoFlame Sensor Module1 x BuzzerJumper wiresBreadboard"],
    connections: ["Flame Sensor OUT → Arduino Digital Pin 7Flame Sensor VCC → 5VFlame Sensor GND → GNDLED / Buzzer → Arduino Digital Pin 13Power supply: 5V (Arduino USB or adapter)"],
    steps: ["Connect the flame sensor to the Arduino as per the circuit diagram.", "Connect the Arduino to the computer using a USB cable.", "Open Arduino IDE and select the correct board and COM port.", "Upload the flame detector program to the Arduino.", "Power ON the Arduino.", "Bring a flame near the sensor.", "The sensor detects the flame and sends a signal to the Arduino.", "The LED or buzzer turns ON as an alert.", "When the flame is removed, the alert turns OFF."],
    working: "The flame sensor detects infrared (IR) radiation emitted by fire.When a flame is present, the sensor output changes and sends a digital signal to the Arduino.The Arduino continuously monitors this signal.If a flame is detected, the Arduino turns ON the LED or buzzer to provide an alert.When no flame is present, the alert device remains OFF.",
    references: ["[1]\tBharsakade et al., Advanced Fire & Gas Detection System, IJRaset.", "[2]\tArduino, Digital Input and Output, Arduino.cc."],
    driveLink: "/word-files/(16)Flame%20Detector.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "DIY Flashlight",
    description: "The DIY Flashlight project demonstrates the basic working of an electric circuit using simple components such as a cell, LED, and copper tape.In this project, a flashlight is made by mounting an LED inside a flashlight cutout and completing the circuit using copper tape as conducting paths.This project helps beginners understand basic electrical concepts such as current flow, polarity, and circuit completion.",
    type: ProjectType.BASIC,
    category: "DIY & Crafts",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["1 x Battery Cell (1.5V or 3V coin cell)1 x LEDCopper TapeFlashlight Cutout / Cardboard HolderInsulating tapeScissors"],
    connections: ["Positive terminal of the battery → Copper tape strip → LED Anode (+)LED Cathode (–) → Copper tape strip → Negative terminal of the battery"],
    steps: ["Fix the LED inside the flashlight cutout.", "Paste copper tape to form conductive paths for the positive and negative terminals.", "Place the battery cell in the holder such that it touches the copper tape strips.", "Ensure the LED polarity is correctly connected.", "When the circuit is completed, the LED glows, acting as a flashlight.", "Breaking the circuit (by removing the battery or disconnecting tape) turns OFF the LED.", "Conclusion: (Predefined/self-written)", "The DIY Flashlight project is a simple and effective way to understand basic electronics and circuit connections.It demonstrates how electrical energy from a battery can be converted into light energy using an LED.This project is ideal for beginners and school-level demonstrations."],
    working: "The DIY flashlight works on the principle of a closed electrical circuit.When the battery terminals are connected to the LED through copper tape, electric current flows through the LED.The LED converts electrical energy into light energy.Copper tape acts as a conductor, allowing current to flow with minimal resistance.",
    references: [],
    driveLink: "/word-files/(17)DIY%20Flashlight.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Water Level Indicator",
    description: "The Water Level Indicator is an electronic system used to monitor and indicate the level of water in a tank or reservoir. It helps users identify whether the water level is low, medium, or high and provides alerts to prevent overflow and dry running of pumps. This system ensures efficient water usage and reduces wastage by giving timely indications.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Servo"],
    components: ["Arduino Uno / Nano", "Water sensor", "2 x LED (with 220Ω resistor)", "1 x Buzzer", "Jumper wires", "Breadboard"],
    connections: ["Arduino Pin A0 → water sensor", "Arduino Pin 10 → Buzzer", "Arduino Pin 8,9 → LED", "Power supply: 5V (from Arduino USB or adapter)"],
    steps: ["Insert water sensor at the desired level inside the water tank.", "Upload the Arduino code to the board.", "Connect the components as per the pinout.", "Power ON the system.", "When water touches the probes → LED glows and buzzer beeps.", "When water level drops → alert stops automatically."],
    working: "The water level indicator works on the principle of water conductivity. Water acts as a conductor of electricity. When the water level rises and comes in contact with the sensor probes, an electrical signal is generated. This signal is detected by the microcontroller, which then activates LEDs or a buzzer to indicate the current water level.",
    references: ["[1] Electronics Tutorials, “Water Level Detector Circuit,” Electronics-tutorials.ws, 2023. [Online]. Available: https://www.electronics-tutorials.ws/water-level-detector. [Accessed: 27-Aug-2025].", "[2] Arduino, “Digital Read Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalread/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(18)Water%20level%20Indicator.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Buzzer Interfacing",
    description: "The Buzzer Interfacing project demonstrates how to interface a buzzer with an Arduino to produce sound alerts.A buzzer is an audio output device that generates sound when an electrical signal is applied.This project is commonly used in alarm systems, notification systems, and warning indicators",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "Buzzer"],
    components: ["Arduino Uno / Nano1 x Buzzer (Active)Jumper wiresBreadboard"],
    connections: ["Arduino Pin 9 → Buzzer (+)Buzzer (–) → GND", "Power supply: 5V (from Arduino USB or adapter)"],
    steps: ["Connect the buzzer to the Arduino as per the circuit connection.Upload the buzzer interfacing code to the Arduino board.Power ON the Arduino using USB or adapter.The buzzer will turn ON for a fixed duration.After the delay, the buzzer will turn OFF automatically.This process repeats continuously."],
    working: "The project works on the principle of digital output control.When Arduino sends a HIGH signal to the buzzer pin, current flows through the buzzer and it produces sound.When the signal is LOW, the buzzer stops producing sound.",
    references: ["[1] Arduino, “Tone Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/advanced-io/tone/. [Accessed: 27-Aug-2025].", "[2] Arduino, “Digital Write Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalwrite/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(19)Buzzer%20Interfacing%20using%20Arduino.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Simple Windmill",
    description: "A basic windmill project using a DC motor and fan blades to demonstrate energy conversion from wind to electrical energy.",
    type: ProjectType.BASIC,
    category: "Mechanics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Motor"],
    components: ["DC Motor", "Fan Blade", "LED", "Resistor", "Wooden/Plastic base"],
    connections: ["DC Motor → connected to fan blade", "Motor terminals → LED with resistor or small load"],
    steps: ["Fix DC motor to a base.", "Attach fan blade to motor shaft.", "Connect motor terminals to LED with resistor.", "Blow air or use fan to rotate blade.", "Observe LED glow."],
    working: "The fan blades rotate when wind is applied, spinning the DC motor, which generates electricity to power an LED.",
    references: ["[1] Electronics Tutorials, 'DC Motor Basics,' https://www.electronics-tutorials.ws/dcmotor"],
    driveLink: "/word-files/(2)Simple_Windmill.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "DIY Bookmark",
    description: "The DIY Bookmark project is a simple, electronic craft-based project designed to help students create a useful reading accessory.It encourages creativity and basic design skills while providing a practical solution for marking pages in books.This project is low-cost, easy to make, and suitable for beginners.",
    type: ProjectType.BASIC,
    category: "DIY & Crafts",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: [],
    components: ["PaperColor paperSketch pens / MarkersScaleScissorsGlue / TapeDecorative materials (optional)"],
    connections: [],
    steps: ["Cut the cardboard or thick paper into a rectangular shape.Design the bookmark using color paper or sketch pens.Decorate the bookmark as desired.Allow glue to dry completely.Use the bookmark to mark pages while reading.", "Conclusion: (Predefined/self-written)", "The DIY Bookmark project helps develop creativity and organizational skills.It is a simple yet useful project that promotes reading habits and effective learning."],
    working: "The DIY Bookmark works on a manual and creative principle.It is designed to be placed between book pages to mark the last read position.No electrical or mechanical components are involved.",
    references: ["[1] DIY Craft Ideas, “How to Make a Simple Bookmark,” Diycraftsy.com, 2023. [Online]. Available: https://www.diycraftsy.com/diy-bookmark/. [Accessed: 27-Aug-2025].", "[2] Instructables, “DIY Paper Bookmark,” Instructables.com, 2022. [Online]. Available: https://www.instructables.com/DIY-Paper-Bookmark/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(20)DIY%20Bookmark.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Simple LED Blink",
    description: "The Simple LED Blink project is a basic Arduino project used to understand digital output control.In this project, an LED is connected to an Arduino board and is programmed to turn ON and OFF at a fixed time interval.This project helps beginners learn how microcontrollers control electronic components and understand delay functions.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "LED"],
    components: ["Arduino Uno / Nano1 x LED1 x 220Ω ResistorJumper wiresBreadboard"],
    connections: ["Arduino Pin 13 → LED (with 220Ω resistor)LED Cathode → GND", "Power supply: 5V (from Arduino USB or adapter)"],
    steps: ["Connect the LED to Arduino as per the circuit diagram.Upload the LED blink program to the Arduino board.Power ON the Arduino using USB or adapter.The LED will turn ON for a fixed duration.After the delay, the LED will turn OFF automatically.This cycle repeats continuously."],
    working: "The project works on the principle of digital signal control.Arduino sends a HIGH signal (5V) to the LED pin, allowing current to flow and turn the LED ON.When the signal is LOW (0V), the current stops and the LED turns OFF.",
    references: ["[1] Arduino, “Blink Example,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Tutorial/BuiltInExamples/Blink. [Accessed: 27-Aug-2025].", "[2] Arduino, “Digital Write Function,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalwrite/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(21)Simple%20LED%20blink%20using%20Arduino.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Automatic Hand Sanitizer Dispenser",
    description: "The Automatic Hand Sanitizer Dispenser is a contactless hygiene system designed to dispense sanitizer automatically when a hand is detected.This project helps reduce physical contact and prevents the spread of germs.It uses an ultrasonic sensor to detect the presence of a hand and a servo motor to press or release the sanitizer container mechanism.",
    type: ProjectType.BASIC,
    category: "Smart Home",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Sensor", "Motor", "Servo"],
    components: ["Arduino Uno / NanoUltrasonic Sensor (HC-SR04)Servo Motor (SG90 or equivalent)9V BatteryHand Sanitizer ContainerJumper wiresBreadboard"],
    connections: ["Ultrasonic Sensor TRIG → Arduino Pin 9Ultrasonic Sensor ECHO → Arduino Pin 10Ultrasonic Sensor VCC → 5VUltrasonic Sensor GND → GND", "Servo Motor Signal → Arduino Pin 6Servo Motor VCC → 5VServo Motor GND → GND", "Power Supply: 9V Battery (connected to Arduino VIN)"],
    steps: ["Mount the ultrasonic sensor near the sanitizer outlet.", "Connect all components as per the circuit diagram.", "Upload the Arduino code to the board.", "Power ON the system using a 9V battery.", "When a hand comes close to the sensor, distance reduces.", "Arduino detects the hand and activates the servo motor.", "Servo motor presses the sanitizer container.", "Sanitizer is dispensed automatically.", "Servo returns to its initial position."],
    working: "The project works on the principle of ultrasonic distance measurement.The ultrasonic sensor emits high-frequency sound waves and measures the time taken for the echo to return.When a hand is placed within a predefined distance, the Arduino detects it.The Arduino then rotates the servo motor, which presses the sanitizer container to dispense sanitizer.After a short delay, the servo returns to its original position.",
    references: ["[1] Arduino, Ultrasonic Sensor with Arduino, Arduino.cc", "[2] Electronics Hub, “Automatic Hand Sanitizer Dispenser using Arduino,” Electronicshub.org, 2023. [Online]. Available: https://www.electronicshub.org/automatic-hand-sanitizer-dispenser/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(22)Automatic%20Hand%20Sanitizer%20Dispenser.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Buzzer Interfacing Using Esp32",
    description: "The Buzzer Interfacing project using ESP32 demonstrates how to interface a buzzer with a Wi-Fi enabled microcontroller to produce sound alerts.A buzzer is an audio output device that generates sound when an electrical signal is applied.This project is commonly used in alarm systems, notification systems, and warning indicators.",
    type: ProjectType.IOT,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["ESP32", "LED", "Buzzer"],
    components: ["ESP32 Development Board1 x Active BuzzerJumper wiresBreadboard"],
    connections: ["ESP32 GPIO 18 → Buzzer (+)Buzzer (–) → GNDPower supply: 3.3V logic from ESP32 (powered via USB)"],
    steps: ["Connect the buzzer to the ESP32 as per the circuit connection.", "Connect the ESP32 to a computer using a USB cable.", "Select the correct ESP32 board and COM port in the Arduino IDE.", "Upload the buzzer interfacing program to the ESP32.", "Power ON the ESP32.", "The buzzer turns ON for a fixed duration.", "After the delay, the buzzer turns OFF automatically.", "This process repeats continuously."],
    working: "The project works on the principle of digital GPIO control.When the ESP32 sends a HIGH signal (3.3V) to the buzzer pin, current flows through the buzzer and it produces sound.When the signal is LOW, the buzzer stops producing sound.",
    references: ["[1] Espressif Systems, ESP32 GPIO Programming Guide."],
    driveLink: "/word-files/(23)Buzzer%20Interfacing%20using%20Esp32.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "DIY Morse Code Flasher",
    description: "The DIY Morse Code Flasher project is designed to transmit messages using light and sound signals based on Morse code.In this project, an LED flashes and a buzzer beep in short and long intervals representing dots and dashes.A push button is used to manually trigger the Morse code signal.This project helps students understand basic communication systems, timing control, and input–output interfacing using Arduino.",
    type: ProjectType.BASIC,
    category: "DIY & Crafts",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "LED", "Buzzer"],
    components: ["Arduino Uno 1 x LED1 x 220Ω Resistor1 x Buzzer1 x Push ButtonJumper wiresBreadboard"],
    connections: ["Arduino Pin 13 → LED (with 220Ω resistor)LED Cathode → GND", "Arduino Pin 8 → Buzzer (+)Buzzer (–) → GND", "Arduino Pin 2 → Push ButtonPush Button (other terminal) → GND", "Power supply: 5V (from Arduino USB or adapter)"],
    steps: ["Connect the LED, buzzer, and push button to the Arduino as per the circuit diagram.", "Upload the Morse code flasher program to the Arduino board.", "Power ON the Arduino using USB or adapter.", "Press the push button to start transmission.", "The LED flashes and buzzer beeps in Morse code pattern.", "The message repeats whenever the button is pressed."],
    working: "The project works on the principle of timed digital output signals.The push button acts as an input to the Arduino.When the button is pressed, the Arduino activates the LED and buzzer.Short ON durations represent dots, and long ON durations represent dashes in Morse code.By controlling the timing, the Arduino transmits a predefined Morse code message.",
    references: ["[1] Arduino, “Blink Example,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Tutorial/BuiltInExamples/Blink. [Accessed: Jan. 10, 2026].", "[2] International Telecommunication Union (ITU), “Morse Code Signals,” ITU Publications. [Online]. Available: https://www.itu.int/rec/R-REC-M.1677. [Accessed: Jan. 10, 2026]."],
    driveLink: "/word-files/(24)DIY%20Morse%20Code%20Flasher.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Temperature and Humidity Indicator",
    description: "The Temperature and Humidity Indicator project is designed to measure and display environmental temperature and humidity.In this project, a DHT11 sensor is used to sense temperature and relative humidity, and the values are displayed through the Serial Monitor.This project helps students understand sensor interfacing, data acquisition, and environmental monitoring using Arduino.",
    type: ProjectType.BASIC,
    category: "Weather Station",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "Sensor"],
    components: ["Arduino Uno / NanoDHT11 Temperature and Humidity SensorJumper wiresBreadboard"],
    connections: ["DHT11 DATA → Arduino Pin 2DHT11 VCC → 5VDHT11 GND → GNDPower supply: 5V"],
    steps: ["Connect the DHT11 sensor to the Arduino as per the circuit diagram.", "Connect the Arduino to the computer using a USB cable.", "Install the DHT sensor library in the Arduino IDE.", "Upload the temperature and humidity indicator program to the Arduino.", "Open the Serial Monitor.", "The current temperature and humidity values are displayed continuously."],
    working: "The DHT11 sensor contains a temperature sensor and a humidity sensor along with an internal ADC.It measures ambient temperature in degrees Celsius and relative humidity in percentage.The sensor sends digital data to the Arduino through a single data pin.Arduino reads this data and displays the temperature and humidity values on the Serial Monitor.",
    references: ["[1] Arduino, “DHT Sensor Library,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/libraries/dht-sensor-library/. [Accessed: Jan. 15, 2026].", "[2] Aosong Electronics Co., Ltd., “DHT11 Temperature and Humidity Sensor Datasheet,” Aosong Electronics. [Online]. Available: https://components101.com/sensors/dht11-temperature-sensor. [Accessed: Jan. 15, 2026]."],
    driveLink: "/word-files/(25)Temperature%20and%20Humidity%20Indicator.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Hand Gesture Controlled Fan",
    description: "The Hand Gesture Controlled Fan project is designed to control a fan using hand movement without physical contact.In this project, an IR sensor detects the presence of a hand, and a relay module is used to switch a DC motor with a propeller ON or OFF.The system operates using a battery supply, making it suitable for basic automation and contactless control applications.",
    type: ProjectType.BASIC,
    category: "Smart Home",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["LED", "Sensor", "Motor"],
    components: ["Arduino Uno DC MotorPropellerIR Sensor ModuleRelay Module5 × 1.5V Battery CellsBattery HolderJumper wiresBreadboard"],
    connections: ["IR Sensor OUT → Control Input (Relay trigger / control pin)IR Sensor VCC → Battery Supply (+)IR Sensor GND → Battery Supply (–)", "Relay COM → Battery (+)Relay NO → DC Motor (+)DC Motor (–) → Battery (–)", "Power Supply: 5 × 1.5V cells (7.5V total)"],
    steps: ["Connect the IR sensor, relay, and motor as per the circuit diagram.", "Fix the propeller to the DC motor shaft.", "Insert the 1.5V cells into the battery holder.", "Power ON the system.", "Move your hand in front of the IR sensor.", "The sensor detects the hand gesture.", "Relay turns ON and supplies power to the motor.", "The motor rotates and the fan starts.", "Removing the hand turns the fan OFF.\\"],
    working: "The project works on the principle of infrared sensing and electromechanical switching.When a hand is moved in front of the IR sensor, the reflected infrared rays are detected.The IR sensor output activates the relay module.The relay acts as a switch, allowing battery power to reach the DC motor.The motor rotates the propeller, acting as a fan.When the hand is removed, the relay turns OFF, stopping the motor.",
    references: ["[1] Arduino, “IR Sensor Interfacing with Arduino,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Tutorial/IRSensor. [Accessed: Jan. 15, 2026].", "[2] Electronics Hub, “DC Motor Control Using Relay,” Electronicshub.org. [Online]. Available: https://www.electronicshub.org/dc-motor-control-using-relay/. [Accessed: Jan. 15, 2026]."],
    driveLink: "/word-files/(26)Hand%20Gesture%20Controlled%20Fan.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Night Lamp",
    description: "The Table Night Lamp project is a simple electrical circuit designed to provide soft illumination for use on a table or bedside.In this project, an LED acts as the light source, a switch is used to manually control the lamp, and a coin cell battery provides power.This project helps beginners understand basic circuit connections, switching operations, and LED control.",
    type: ProjectType.BASIC,
    category: "DIY & Crafts",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["LEDSwitchCoin Cell Battery (with holder)", "Wires"],
    connections: ["Coin Cell Battery (+) → SwitchSwitch → LED Anode (+)LED Cathode (–) → Coin Cell Battery (–)", "Power Supply: Coin Cell Battery (3V) using holder"],
    steps: ["• Connect the LED, switch, and coin cell battery as per the circuit diagram.• Place the coin cell into the holder.• Turn ON the switch.• The LED glows, acting as a night lamp.• Turn OFF the switch to stop illumination.", "Conclusion: (Predefined/self-written)", "The Table Night Lamp project demonstrates a basic lighting system using simple electronic components.It helps students understand battery operation, LED polarity, and manual switching control.This project is ideal for beginners and can be extended by adding multiple LEDs or decorative enclosures."],
    working: "The Table Night Lamp works on the principle of a closed electrical circuit.When the switch is turned ON, the circuit is completed, allowing current to flow from the coin cell battery to the LED.The LED converts electrical energy into light energy, providing illumination.When the switch is turned OFF, the circuit breaks and the LED turn OFF.",
    references: ["[1] Components101, “Light Emitting Diode (LED),” Components101.com. [Online]. Available: https://components101.com/diodes/led-light-emitting-diode. [Accessed: Jan. 15, 2026].", "[2] All About Circuits, “Basic Electrical Circuits,” AllAboutCircuits.com. [Online]. Available: https://www.allaboutcircuits.com/textbook/direct-current/chpt-1/what-is-a-circuit/. [Accessed: Jan. 15, 2026]."],
    driveLink: "/word-files/(27)Night%20Lamp.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Light Intensity Changing Using Arduino",
    description: "The Light Intensity Changing project demonstrates how the brightness of an LED can be controlled smoothly using a potentiometer.In this project, a B10k potentiometer is used as an input device to vary voltage, while an Arduino processes this input and adjusts the LED brightness using Pulse Width Modulation (PWM).This project is useful for understanding analog input, PWM output, and basic brightness control applications.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "LED"],
    components: ["Arduino Uno", "B10k Potentiometer", "LED", "220Ω Resistor", "Breadboard", "Jumper Wires"],
    connections: ["Potentiometer Middle Pin → Arduino A0", "Potentiometer Side Pin 1 → Arduino 5V", "Potentiometer Side Pin 2 → Arduino GND", "Arduino PWM Pin (D9) → LED Anode", "LED Cathode → GND (through resistor)"],
    steps: ["• Connect the potentiometer and LED as per the circuit diagram• Upload the Arduino code to the board• Rotate the potentiometer knob• The analog value changes• Arduino adjusts the PWM signal• LED brightness increases or decreases smoothly"],
    working: "The potentiometer acts as a variable voltage divider.When the knob of the potentiometer is rotated, the output voltage changes between 0V and 5V.The Arduino reads this voltage using its analog-to-digital converter (ADC).Based on the input value, the Arduino generates a PWM signal to control the LED brightness.Higher PWM duty cycle increases brightness, while lower duty cycle reduces brightness.",
    references: ["[1] M. Margolis, Arduino Cookbook, 2nd ed. Sebastopol, CA, USA: O’Reilly Media, 2011.", "[2] A. P. Godse and D. A. Godse, Microcontrollers and Applications, Pune, India: Technical Publications, 2010.", "[3] Arduino, “Analog Input and PWM Output,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Tutorial/AnalogInput. [Accessed: Mar. 12, 2015]."],
    driveLink: "/word-files/(28)Light%20Intensity%20Changing%20Using%20Arduino.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Battery Level Indicator",
    description: "The Battery Level Indicator project is a simple electronic circuit used to display the approximate charge level of a battery using LEDs.In this project, four LEDs glow progressively to indicate different voltage levels of a 9V battery.It is a basic and effective way to understand voltage indication, LED operation, and resistor usage in electronic circuits.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["4 × LEDs", "4 × 1kΩ Resistors", "1 × 9V Battery", "Battery Connector", "Breadboard", "Jumper Wires"],
    connections: ["9V Battery (+) → 1kΩ Resistors → LED Anodes", "LED Cathodes → 9V Battery (–)", "Each LED is connected in parallel with its own 1kΩ resistor"],
    steps: ["• Connect the 9V battery to the breadboard• Connect each LED in series with a 1kΩ resistor• Connect all LED-resistor pairs in parallel across the battery• Power ON the circuit• Observe the LEDs glowing based on the battery voltage• More LEDs ON indicate higher battery level• Fewer LEDs ON indicate lower battery level"],
    working: "The battery level indicator works on the principle of voltage division and LED forward voltage characteristics.Each LED requires a minimum voltage to turn ON.As the battery voltage increases, more LEDs receive sufficient voltage and glow.Thus, the number of glowing LEDs indicates the approximate battery charge level.",
    references: ["[1] A. P. Godse and U. A. Bakshi, Electronic Devices and Circuits, 2nd ed. Pune, India: Technical Publications, 2016."],
    driveLink: "/word-files/(29)Battery%20Level%20Indicator.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Automatic Room Light",
    description: "A project using a Light Dependent Resistor (LDR) to detect light intensity and control an LED or light bulb accordingly.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["Arduino UNO", "LDR", "10kΩ Resistor", "LED", "220Ω Resistor", "Breadboard", "Jumper wires"],
    connections: ["LDR → Analog Input A0 on Arduino", "10kΩ Resistor → connected with LDR for voltage divider", "LED → Digital Pin 9 (with 220Ω resistor)"],
    steps: ["Power the Arduino.", "LDR senses ambient light.", "Arduino compares LDR value with threshold.", "If dark → LED turns ON.", "If bright → LED turns OFF."],
    working: "The LDR changes its resistance based on the light falling on it. Arduino reads the voltage from the voltage divider and switches the LED ON/OFF depending on threshold.",
    references: ["[1] Arduino.cc, 'Analog Read Reference,' https://www.arduino.cc/en/Reference/AnalogRead"],
    driveLink: "/word-files/(3)Automatic_Room_Light.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "DC Motor Speed Control Using Arduino",
    description: "The DC Motor Speed Control project is used to control the rotational speed of a DC motor using a potentiometer.In this project, a B10k potentiometer provides variable input to the Arduino, which generates a PWM signal.The L298 motor driver is used to interface the low-power Arduino with the high-current DC motor.A battery supply is used to power the motor, making the system suitable for basic motor control applications.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Arduino", "Motor"],
    components: ["Arduino Uno", "DC Motor", "L298 Motor Driver Module", "B10k Potentiometer", "6 × 1.5V AA Batteries", "Battery Holder", "Jumper Wires", "Breadboard"],
    connections: ["Potentiometer Middle Pin → Arduino A0", "Potentiometer Side Pin 1 → Arduino 5V", "Potentiometer Side Pin 2 → Arduino GND", "Arduino D9 (PWM) → L298 ENA", "Arduino D8 → L298 IN1", "Arduino D7 → L298 IN2", "L298 OUT1 & OUT2 → DC Motor Terminals", "L298 Motor Supply (Vs) → 6 × AA Battery Pack (+)", "L298 GND → Battery (–) and Arduino GND (Common Ground)"],
    steps: ["• Connect the potentiometer, Arduino, L298, and motor as per the circuit• Insert AA batteries into the holder• Upload the motor speed control program• Power ON the Arduino and motor supply• Rotate the potentiometer knob• Motor speed increases or decreases accordingly"],
    working: "The potentiometer acts as a variable voltage divider.Arduino reads the analog voltage and converts it into a digital value.Based on this value, Arduino generates a PWM signal at the ENA pin of the L298 driver.The L298 controls the power supplied to the DC motor, thereby controlling its speed.Changing the potentiometer position varies the motor speed smoothly.",
    references: ["[1] M. Margolis, Arduino Cookbook, 2nd ed. Sebastopol, CA, USA: O’Reilly Media, 2011.", "[2] Arduino, “PWM – Analog Write,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Tutorial/PWM. [Accessed: Apr. 10, 2016].", "[3] Texas Instruments, “L298 Dual Full-Bridge Driver Datasheet,” 2014."],
    driveLink: "/word-files/(30)DC%20Motor%20Speed%20Control%20Using%20Arduino.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "LED Blink Using ESP32 with Wi-Fi",
    description: "The LED Blink Using ESP32 with Wi-Fi project demonstrates how an ESP32 microcontroller can connect to a wireless network and control an LED.In this project, the ESP32 connects to a Wi-Fi network and hosts a simple web server.When accessed through a web browser, the server allows the user to turn the LED ON or OFF wirelessly.This project introduces basic concepts of IoT, Wi-Fi communication, and remote device control.",
    type: ProjectType.IOT,
    category: "Electronics",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["ESP32", "LED", "WiFi"],
    components: ["ESP32 Development Board", "1 × LED", "1 × 220Ω Resistor", "Jumper Wires", "Breadboard", "Wi-Fi Network"],
    connections: ["ESP32 GPIO 2 → LED Anode (via 220Ω resistor)", "LED Cathode → GND", "Power Supply → 5V (USB cable to ESP32)"],
    steps: ["• Connect the LED to the ESP32 GPIO pin using a resistor• Upload the Wi-Fi LED control program to the ESP32• Power ON the ESP32 using a USB cable• Open the Serial Monitor to note the ESP32 IP address• Enter the IP address in a web browser• Click ON/OFF buttons to control the LED wirelessly"],
    working: "The ESP32 has an inbuilt Wi-Fi module.After connecting to a Wi-Fi network, the ESP32 runs a web server.When a user accesses the ESP32 IP address through a browser, control commands are sent.Based on these commands, the ESP32 changes the state of the GPIO pin, causing the LED to turn ON or OFF.",
    references: ["[1] Espressif Systems, ESP32 Series Datasheet, Espressif Systems Inc., 2016.", "[2] Arduino, “WiFi Library for ESP32,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Reference/WiFi [Accessed: Jun. 12, 2018].", "[3] N. Kolban, Kolban’s Book on ESP32, 1st ed. USA, 2017.", "[4] Arduino, “Web Server with ESP32,” Arduino Project Hub, 2019."],
    driveLink: "/word-files/(31)LED%20Blink%20Using%20ESP32%20with%20Wifi.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Buzz Wire Game (Steady Hand Game)",
    description: "",
    type: ProjectType.BASIC,
    category: "Smart Home",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: [],
    components: ["Metal wire shaped as path", "Buzzer", "LED", "Power supply", "Jumper wires", "Working Principle:The bent wire and loop act as electrical contacts. When the loop touches the wire, the circuit closes. Arduino (or direct connection) detects this event and triggers the buzzer and LED. If no contact is made, the circuit remains open and the player continues. This simple principle of circuit closure forms the basis of many interactive games."],
    connections: [" Power Supply (+) → Bent Metal Wire", " Loop Wire → LED (+) and Buzzer (+)", " LED (–) → GND (via resistor if required)", " Buzzer (–) → GND", " Power Supply (–) → GND"],
    steps: ["• Arrange the bent wire in a desired shape• Connect the circuit as per the diagram• Power ON the system• Move the loop along the wire carefully• If the loop touches the wire → LED glows and buzzer sounds• If the loop does not touch the wire → no output• The game continues until the end of the wire track", "Conclusion:The Buzz Wire Game demonstrates practical application of electrical contact detection and provides an enjoyable way to test hand–eye coordination. It’s an engaging project for beginners to understand open and closed circuits, while making electronics interactive and fun.References:[1] Arduino Project Hub, “Steady Hand Game,” Arduino.cc, 2019. [Online]. Available: https://projecthub.arduino.cc. [Accessed: Sep. 13, 2025].[2] C. Platt, “Make: Electronics,” 2nd ed., Maker Media, 2015."],
    working: "",
    references: [],
    driveLink: "/word-files/(32)Buzz%20Wire%20Game.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Buzzing Buzzer Using ESP32 with Wi-Fi",
    description: "The Buzzing Buzzer Using ESP32 with Wi-Fi project demonstrates how a buzzer can be controlled wirelessly using an ESP32 microcontroller.In this project, the ESP32 connects to a Wi-Fi network and hosts a simple web server.Using a web browser, the user can remotely turn the buzzer ON or OFF.This project introduces basic IoT concepts such as wireless communication, web-based control, and GPIO interfacing.",
    type: ProjectType.IOT,
    category: "Electronics",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["ESP32", "LED", "Buzzer", "WiFi"],
    components: ["ESP32 Development Board", "1 × Active Buzzer", "Jumper Wires", "Breadboard", "Wi-Fi Network"],
    connections: ["ESP32 GPIO 4 → Buzzer (+)", "Buzzer (–) → GND", "Power Supply → 5V (USB cable to ESP32)"],
    steps: ["• Connect the buzzer to the ESP32 GPIO pin• Upload the Wi-Fi buzzer control program to the ESP32• Power ON the ESP32 using a USB cable• Open the Serial Monitor to note the ESP32 IP address• Enter the IP address in a web browser• Press ON/OFF buttons to control the buzzer wirelessly"],
    working: "The ESP32 has a built-in Wi-Fi module that allows it to connect to a wireless network.After connecting to Wi-Fi, the ESP32 runs a web server.When a user accesses the ESP32 IP address through a browser, control commands are sent.Based on the received command, the ESP32 sets the buzzer GPIO pin HIGH or LOW, causing the buzzer to turn ON or OFF.",
    references: ["[1] Espressif Systems, ESP32 Series Datasheet, Espressif Systems Inc., 2016.", "[2] N. Kolban, Kolban’s Book on ESP32, 1st ed., USA, 2017.", "[3] Arduino, “WiFi Library for ESP32,” Arduino.cc. [Online]. Available: https://www.arduino.cc/en/Reference/WiFi. [Accessed: Jun. 10, 2018].", "[4] Arduino, “Digital Output Control,” Arduino.cc. [Online]. Available: https://www.arduino.cc/reference/en/language/functions/digital-io/digitalwrite/. [Accessed: May 12, 2017]."],
    driveLink: "/word-files/(33)Buzzing%20Buzzer%20Using%20ESP32%20with%20WiFi.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Ultrasonic Servo Radar Project",
    description: "This project simulates a simple radar system using an ultrasonic sensor mounted on a servo motor. The servo rotates left and right while the ultrasonic sensor measures distance and scans the surroundings.",
    type: ProjectType.BASIC,
    category: "Mechanics",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Sensor", "Motor", "Servo"],
    components: ["- Arduino UNO- Ultrasonic Sensor (HC-SR04)- Servo Motor (SG90)- Jumper Wires- Breadboard (optional)"],
    connections: ["Servo Motor → PWM Pin (e.g., D9)Ultrasonic Sensor Trig → D10Ultrasonic Sensor Echo → D11VCC and GND common for all components"],
    steps: ["1. Connect the ultrasonic sensor to the Arduino.2. Connect the servo motor to a PWM pin.3. Upload the radar scanning code.4. Servo rotates, sensor detects distance at each angle.5. Output shown on Serial Monitor."],
    working: "The servo motor rotates from 0° to 180° while the ultrasonic sensor takes distance measurements. Each angle's distance is recorded to simulate radar scanning. The data can be viewed on the serial monitor or plotted.",
    references: [],
    driveLink: "/word-files/(34)Rotating_Radar.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Water Pump Interfacing",
    description: "Water Pump Interfacing is a basic electronics project that demonstrates how a submersible water pump can be controlled using a simple switch and battery. When the switch is turned ON, the circuit completes and the water pump starts pumping water. When the switch is OFF, the circuit breaks and the pump stop. This project helps understand basic circuit control and switching in electronics.",
    type: ProjectType.BASIC,
    category: "Mechanics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["Submersible Water Pump (5V)", "9V Battery", "Switch", "Connecting wires"],
    connections: ["9V Battery Positive (+) → Switch", "Switch Output → Positive terminal of Water Pump", "Water Pump Negative terminal → 9V Battery Negative (GND)"],
    steps: ["Connect the positive terminal of the battery to the switch.", "Connect the switch output to the positive terminal of the water pump.", "Connect the negative terminal of the water pump to the battery negative terminal.", "Turn ON the switch to start the pump.", "Turn OFF the switch to stop the pump.", "Conclusion: (Predefined/self-written)", "The Water Pump Interfacing project demonstrates a simple method to control a water pump using a manual switch. It is useful for understanding basic electrical circuits and switching operations and can be extended to automated systems using sensors and microcontrollers."],
    working: "The project works on the principle of manual switching in an electrical circuit.When the switch is turned ON, it completes the circuit and allows current from the battery to flow through the pump, causing it to run. When the switch is turned OFF, the circuit opens and current stops flowing, turning the pump OFF.",
    references: ["Arduino Project Hub – Basic Electronics Projects", "Electronics Tutorials – Switch Controlled Circuits"],
    driveLink: "/word-files/(35)Mini_Water_Pump.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Smart Parking System",
    description: "The Smart Parking System is an electronics project that helps drivers park vehicles safely by measuring the distance between the car and a wall or obstacle. An ultrasonic sensor detects the distance. If the vehicle gets close to the wall, a yellow LED glows as a warning. When the vehicle is very close, a red LED lights up and a buzzer sounds to alert the driver to stop.",
    type: ProjectType.BASIC,
    category: "Automation",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["LED", "Sensor", "Buzzer"],
    components: ["Arduino UNO", "Ultrasonic Sensor (HC-SR04)", "Yellow LED", "Red LED", "Buzzer", "2 × 220Ω Resistors", "Breadboard", "Jumper wires"],
    connections: ["Ultrasonic Sensor (HC-SR04) → Arduino", "Ultrasonic Pin", "Arduino", "VCC", "5V", "GND", "GND", "TRIG", "D9", "ECHO", "D10", "Component", "Arduino Pin", "Yellow LED", "D6", "Red LED", "D7", "Buzzer", "D8", "Each LED positive → 220Ω resistor → Arduino pinEach LED negative → GND"],
    steps: ["Power ON the Arduino system.", "The ultrasonic sensor continuously measures distance.", "Arduino calculates the distance from the sensor data.", "If the car approaches the wall, the yellow LED turns ON.", "If the car gets very close, the red LED and buzzer activate.", "This alerts the driver to stop the vehicle."],
    working: "The ultrasonic sensor works on the principle of sound wave reflection. It sends ultrasonic waves and receives the reflected signal from the obstacle. Arduino calculates the distance using the time taken for the echo to return. Based on this distance, the system activates warning indicators.\nDistance > 20 cm → Safe (no LED)\nDistance between 10–20 cm → Yellow LED ON (vehicle close)\nDistance < 10 cm → Red LED ON + buzzer (vehicle very close)",
    references: ["Arduino Project Hub – Ultrasonic Sensor Tutorial", "Electronics Tutorials – Distance Measurement using HC-SR04"],
    driveLink: "/word-files/(36)Smart%20parking%20system.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Rainfall Rate Detector",
    description: "The Rainfall Rate Detector is a simple electronics project that detects the intensity of rainfall using a rain drop sensor. The system indicates the rainfall level using three LEDs. When there is no rain, the green LED glows. During moderate rain, the yellow LED glows, and during heavy rainfall, the red LED glows. This project helps in understanding rain detection and visual indication using sensors and LEDs.",
    type: ProjectType.BASIC,
    category: "Sensors & Alarms",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED", "Sensor"],
    components: ["Arduino UNO", "Rain Drop Sensor Module", "Green LED", "Yellow LED", "Red LED", "3 × 220Ω Resistors", "Breadboard", "Jumper wires"],
    connections: ["Rain Sensor → Arduino", "Rain Sensor Pin", "Arduino", "VCC", "5V", "GND", "GND", "AO", "A0", "LED Connections", "LED", "Arduino Pin", "Green LED", "D8", "Yellow LED", "D9", "Red LED", "D10", "Each LED positive → 220Ω resistor → Arduino pinEach LED negative → GND"],
    steps: ["Power ON the Arduino system.", "The rain sensor continuously monitors the presence of water droplets.", "Arduino reads the analog value from the rain sensor.", "If no rain is detected, the green LED glows.", "If moderate rain occurs, the yellow LED glows.", "If heavy rainfall occurs, the red LED glows."],
    working: "The rain drop sensor detects water droplets on its surface. When rain falls on the sensor plate, its resistance changes, which results in a change in the analog output voltage. Arduino reads this analog value and determines the rainfall intensity. Based on the sensor value, Arduino activates the appropriate LED indicator.",
    references: ["Arduino Project Hub – Rain Sensor Module Tutorial", "Electronics Tutorials – Rain Detection Circuits"],
    driveLink: "/word-files/(37)Rainfall%20rate%20detector.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Smart Dustbin",
    description: "The Smart Dustbin is an automatic waste bin that opens its lid when a person brings their hand close to it. An ultrasonic sensor detects the presence of an object near the bin. The Arduino processes the sensor data and controls a servo motor to open the lid automatically. After a few seconds, the lid closes again. This project helps maintain hygiene and reduces the need to touch the dustbin manually.",
    type: ProjectType.BASIC,
    category: "Smart Home",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Arduino", "Sensor", "Motor", "Servo"],
    components: ["Arduino UNO", "Ultrasonic Sensor (HC-SR04)", "Servo Motor (SG90)", "Cup or small container (used as dustbin)", "Jumper wires", "Breadboard", "Power supply / USB cable"],
    connections: ["Ultrasonic Sensor (HC-SR04) → Arduino", "Ultrasonic Pin", "Arduino", "VCC", "5V", "GND", "GND", "TRIG", "D9", "ECHO", "D10", "Servo Motor → Arduino", "Servo Wire", "Arduino", "Red", "5V", "Brown/Black", "GND", "Orange/Yellow (Signal)", "D6"],
    steps: ["Power ON the Arduino system.", "The ultrasonic sensor continuously measures the distance.", "When a hand or object comes within a set distance (for example 15 cm), the sensor sends the data to Arduino.", "Arduino processes the signal and rotates the servo motor to open the dustbin lid.", "After a short delay, the servo motor rotates back to close the lid."],
    working: "The ultrasonic sensor measures the distance between the sensor and any nearby object by sending ultrasonic waves and receiving the reflected signal. When a hand is placed near the bin, the sensor detects a short distance. Arduino then sends a signal to the servo motor to rotate and open the lid. After a few seconds, the servo rotates back and closes the lid automatically.",
    references: ["Arduino Project Hub – Smart Dustbin using Ultrasonic Sensor.", "Electronics Tutorials – Servo Motor Interfacing with Arduino."],
    driveLink: "/word-files/(38)Smart%20Dustbin.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Automatic Barrier Gate System",
    description: "The Automatic Barrier Gate System is a simple automation project used to control a vehicle entry barrier. An ultrasonic sensor detects the presence of a vehicle near the gate. When a vehicle is detected within a certain distance, the Arduino sends a signal to a servo motor which lifts the barrier (straw) upward to allow the vehicle to pass. After a few seconds, the barrier automatically returns to its original position.",
    type: ProjectType.BASIC,
    category: "Automation",
    difficulty: Difficulty.INTERMEDIATE,
    duration: "1-2 hours",
    tags: ["Arduino", "Sensor", "Motor", "Servo"],
    components: ["Arduino UNO", "Ultrasonic Sensor (HC-SR04)", "Servo Motor (SG90)", "Straw (used as barrier gate)", "Breadboard", "Jumper wires", "Power supply / USB cable"],
    connections: ["Ultrasonic Sensor (HC-SR04) → Arduino", "Ultrasonic Pin", "Arduino", "VCC", "5V", "GND", "GND", "TRIG", "D9", "ECHO", "D10", "Servo Motor → Arduino", "Servo Wire", "Arduino", "Red", "5V", "Brown/Black", "GND", "Orange/Yellow (Signal)", "D6"],
    steps: ["Power ON the Arduino system.", "The ultrasonic sensor continuously measures the distance.", "When a vehicle approaches within the preset distance, the sensor detects it.", "Arduino sends a signal to the servo motor.", "The servo motor rotates and raises the straw barrier.", "After a few seconds, the barrier lowers automatically."],
    working: "The ultrasonic sensor measures the distance between the sensor and nearby objects using ultrasonic sound waves. When a vehicle approaches within a specific distance, the sensor detects it and sends the signal to the Arduino. The Arduino processes the signal and commands the servo motor to rotate and lift the barrier. After a short delay, the servo rotates back and lowers the barrier again.",
    references: ["Arduino Project Hub – Smart Dustbin using Ultrasonic Sensor.", "Electronics Tutorials – Servo Motor Interfacing with Arduino."],
    driveLink: "/word-files/(39)Automatic%20barrier%20gate%20system.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Clap Switch",
    description: "",
    type: ProjectType.BASIC,
    category: "Input Devices",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: [],
    components: ["Arduino UNO", "Microphone sound sensor module", "Breadboard", "Led", "Power supply", "Jumper wiresWorking Principle:The microphone sensor detects the sound of a clap and converts it into a voltage signal. The Arduino reads this signal, and when it crosses a threshold, it toggles the output pin connected to the relay. The relay then switches the appliance ON or OFF. A simple transistor circuit can also achieve the same effect without programming.Operation (Step-by-Step):", "Connect microphone sensor to Arduino input.", "Connect relay module to digital output.", "Upload clap switch code.", "Clap near the sensor → appliance toggles ON/OFF."],
    connections: ["Microphone sensor OUT → Arduino digital pin 2", "VCC/GND → Arduino 5V and GND"],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(4)Clap%20Switch.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "ESP32 Digital Thermometer with OLED Display",
    description: "",
    type: ProjectType.IOT,
    category: "Weather Station",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["ESP32", "LED", "Display"],
    components: [],
    connections: ["DHT11/LM35 sensor OUT → GPIO 4", "OLED SDA → GPIO 21", "OLED SCL → GPIO 22", "VCC/GND → 3.3V and GNDComponents Required:", "ESP32", "DHT11 or LM35 temperature sensor", "0.96\" OLED Display (I2C)", "Jumper wiresWorking Principle:The ESP32 reads analog/digital temperature values from the sensor. These values are processed and sent to the OLED display via I2C. The real-time temperature is updated continuously. With Wi-Fi capability, the ESP32 can also transmit the data online for IoT applications.Operation (Step-by-Step):", "Connect sensor and OLED to ESP32.", "Upload thermometer code.", "View temperature on OLED display.", "(Optional) Extend by sending data to cloud."],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(40)ESP32%20Digital%20Thermometer%20with%20OLED.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Digital Dice",
    description: "The Digital Dice is an electronic project that simulates the working of a traditional dice using an ESP32 microcontroller. When the push button is pressed, the ESP32 generates a random number between 1 and 6 and displays it on the OLED display. This project demonstrates the use of random number generation, input buttons, and OLED display interfacing with ESP32.",
    type: ProjectType.IOT,
    category: "Fun & Games",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["ESP32", "LED", "Display"],
    components: ["ESP32 Development Board", "Push Button", "OLED Display (SSD1306)", "Jumper wires", "Breadboard"],
    connections: ["Push Button: One terminal of the push button is connected to GPIO 4 of ESP32, and the other terminal is connected to GND.", "OLED Display: The VCC pin of the OLED is connected to 3.3V of ESP32, the GND pin is connected to GND, the SDA pin is connected to GPIO 21, and the SCL pin is connected to GPIO 22."],
    steps: ["Power ON the ESP32 board.", "The OLED display initializes and waits for input.", "When the push button is pressed, ESP32 generates a random number between 1 and 6.", "The generated number is displayed on the OLED screen.", "Each time the button is pressed, a new number appears, simulating a dice roll."],
    working: "The push button acts as an input device. When the button is pressed, the ESP32 generates a random number between 1 and 6 using its random number function. The generated number is then sent to the OLED display using the I2C communication protocol, and the number appears on the screen like the result of a dice roll.",
    references: ["[1] Arduino Project Hub, “Interfacing OLED Display with ESP32,” Arduino Project Hub. [Online]. Available: https://projecthub.arduino.cc", "[2] Espressif Systems, “ESP32 Technical Reference Manual,” Espressif Systems, 2023. [Online]. Available: https://www.espressif.com"],
    driveLink: "/word-files/(41)Digital%20Dice.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "LED Greeting Card",
    description: "",
    type: ProjectType.BASIC,
    category: "DIY & Crafts",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: [],
    connections: [],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(5)LED%20Greeting%20Card.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Air Quality Indicator",
    description: "",
    type: ProjectType.BASIC,
    category: "Environment",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: [],
    components: [],
    connections: ["Dust sensor OUT → Arduino A0", "LED → Arduino D9 (via resistor)", "VCC/GND → Arduino power pinsComponents Required:", "Arduino UNO", "Dust sensor module (e.g., GP2Y1010AU0F)", "LED", "Resistor (220Ω)", "Breadboard and wiresWorking Principle:The dust sensor measures the concentration of dust particles in the air by detecting reflected infrared light. The output voltage increases with dust density. Arduino reads this voltage and, if it exceeds a threshold, switches ON the LED as an air quality warning.Operation (Step-by-Step):", "Connect dust sensor to Arduino analog input.", "Upload threshold detection code.", "Place sensor in environment.", "If dust detected → LED lights up."],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(6)Air%20Quality%20Indicator.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Series and Parallel LED circuit",
    description: "This project helps students understand how LEDs behave when connected in series and in parallel. It shows the effect on brightness, power usage, and voltage when more than one LED is connected in different ways.",
    type: ProjectType.BASIC,
    category: "Electronics",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: ["• LEDs • Resistors (220Ω)• Arduino• Breadboard (optional)• Jumper Wires"],
    connections: ["Digital Pin: D8 (or any digital pin)", "GND: GND pin"],
    steps: ["1. Connect the LEDs in series and observe brightness.2. Then connect the LEDs in parallel and observe brightness.3. Compare the difference in glow between the the two setups.4. Understand how current and voltage affect LEDs in each type of connection."],
    working: "In a series circuit, current flows through each LED one after another. This means brightness is usually lower, and all LEDs share the same current. In a parallel circuit, each LED gets the full voltage, so they glow brighter.",
    references: ["[1] SparkFun Electronics, “LEDs and Resistors Basics,” Sparkfun.com, 2023. [Online]. Available: https://learn.sparkfun.com/tutorials/leds. [Accessed: 27-Aug-2025].", "[2] All About Circuits, “Series vs Parallel Circuits,” Allaboutcircuits.com, 2022. [Online]. Available: https://www.allaboutcircuits.com/projects/series-and-parallel-circuits/. [Accessed: 27-Aug-2025]."],
    driveLink: "/word-files/(7)Series_and_Parallel_LED_Circuit.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Memory Game using LEDs",
    description: "",
    type: ProjectType.BASIC,
    category: "Fun & Games",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["LED"],
    components: [],
    connections: [],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(8)Memory%20Game%20using%20LEDs.docx",
    featured: false,
    isPublished: true,
  },
  {
    title: "Mini Piano using Buzzer",
    description: "",
    type: ProjectType.BASIC,
    category: "Fun & Games",
    difficulty: Difficulty.BEGINNER,
    duration: "1-2 hours",
    tags: ["Buzzer"],
    components: ["Arduino UNO", "Buzzer", "Push buttons (5)", "10kΩ resistors", "Breadboard & jumper wires", "Working Principle:Each button is connected to a digital input pin. When pressed, the Arduino detects HIGH input and sends a PWM signal at a specific frequency to the buzzer. Each frequency corresponds to a musical note, e.g., 262 Hz for C, 294 Hz for D, etc. By pressing different buttons, different tones are generated, simulating a mini piano. The tone() function allows precise generation of square waves that drive the buzzer.Operation (Step-by-Step):", "Connect buttons to Arduino inputs.", "Connect buzzer to D9.", "Upload code.", "Press different buttons → buzzer produces musical notes."],
    connections: [],
    steps: [],
    working: "",
    references: [],
    driveLink: "/word-files/(9)Mini%20Piano%20using%20Buzzer.docx",
    featured: false,
    isPublished: true,
  },
]

async function main() {
  console.log('🌱 Seeding database...')

  const hashedPassword = await bcrypt.hash('demo1234', 10)

  let user = await prisma.user.findFirst({
    where: { email: 'demo@pulse.io' }
  })

  if (!user) {
    user = await prisma.user.create({
      data: {
        email: 'demo@pulse.io',
        name: 'Demo User',
        password: hashedPassword,
        role: 'ADMIN',
      }
    })
    console.log('✅ Created demo user')
  } else {
    console.log('ℹ️  Demo user already exists')
  }

  await prisma.project.deleteMany({})
  console.log('🗑️  Cleared existing projects')

  for (const project of projects) {
    await prisma.project.create({
      data: {
        ...project,
        userId: user.id,
        imageUrl: null,
      }
    })
    console.log(`✅ Created: ${project.title}`)
  }

  console.log(`\n🎉 Seeded ${projects.length} projects successfully!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
